-- +goose Up
-- +goose StatementBegin

-- Reseed schools table with fresh data from Dapodik (via datapendidikan.com)
-- Total: 333 sekolah di Kabupaten Tanah Bumbu

DELETE FROM renjana_schools;
-- Seed data from Dapodik (via datapendidikan.com)
INSERT INTO renjana_schools (name, level, status, kecamatan) VALUES
('MA DARUL AZHAR', 'MA', 'Swasta', 'Simpang Empat'),
('MAN TANAH BUMBU', 'MA', 'Negeri', 'Kusan Hilir'),
('MAS AL KAUTSAR', 'MA', 'Swasta', 'Satui'),
('MAS AL-KAUTSAR', 'MA', 'Swasta', 'Kusan Hilir'),
('MAS AZ ZIKRA BATULICIN', 'MA', 'Swasta', 'Batu Licin'),
('MAS Darul Ijabah', 'MA', 'Swasta', 'Batu Licin'),
('MAS HIDAYATUSSALAM', 'MA', 'Swasta', 'Satui'),
('MAS NURUL HIDAYAH', 'MA', 'Swasta', 'Simpang Empat'),
('MAS NURUL WATHAN', 'MA', 'Swasta', 'Mantewe'),
('MAS RIADHUSSHALIHIN', 'MA', 'Swasta', 'Satui'),
('MIN TANAH BUMBU', 'MI', 'Negeri', 'Kusan Hilir'),
('MIS AL - IKHLAS', 'MI', 'Swasta', 'Kusan Hilir'),
('MIS AL AMIN', 'MI', 'Swasta', 'Satui'),
('MIS AL HIDAYAH', 'MI', 'Swasta', 'Batu Licin'),
('MIS AL MUJAHIDIN', 'MI', 'Swasta', 'Satui'),
('MIS AL-KAUTSAR', 'MI', 'Swasta', 'Satui'),
('MIS AT TAQWA', 'MI', 'Swasta', 'Satui'),
('MIS DARUL AZHAR', 'MI', 'Swasta', 'Simpang Empat'),
('MIS DARUL MA''RIFAH', 'MI', 'Swasta', 'Satui'),
('MIS DARUL MUTAMMAM', 'MI', 'Swasta', 'Kusan Hilir'),
('MIS MIFTAHUSSALAM', 'MI', 'Swasta', 'Satui'),
('MIS NURUL HIDAYAH', 'MI', 'Swasta', 'Simpang Empat'),
('MIS SAIRUSSALAM', 'MI', 'Swasta', 'Satui'),
('MIS SULLAMUL KHAIR', 'MI', 'Swasta', 'Kusan Hulu'),
('MIS Syarif Abbas', 'MI', 'Swasta', 'Simpang Empat'),
('MTSS AL HIDAYAH', 'MTs', 'Swasta', 'Batu Licin'),
('MTSS AL ISLAHIYAH', 'MTs', 'Swasta', 'Karang Bintang'),
('MTSS AL ISTIQOMAH', 'MTs', 'Swasta', 'Karang Bintang'),
('MTSS AL KAUTSAR', 'MTs', 'Swasta', 'Satui'),
('MTSS BAHRUL ULUM', 'MTs', 'Swasta', 'Mantewe'),
('MTSS DARUL AZHAR', 'MTs', 'Swasta', 'Simpang Empat'),
('MTSS DARUL ISHLAH NW', 'MTs', 'Swasta', 'Angsana'),
('MTSS DDI KERSIK PUTIH', 'MTs', 'Swasta', 'Batu Licin'),
('MTSS DDI MUARA PAGATAN', 'MTs', 'Swasta', 'Kusan Hilir'),
('MTSS HIDAYATUSSALAM NW', 'MTs', 'Swasta', 'Satui'),
('MTSS MIFTAHUL JANNAH', 'MTs', 'Swasta', 'Kusan Hulu'),
('MTSS MIFTAHUSSALAM', 'MTs', 'Swasta', 'Satui'),
('MTSS NU AL-FALAH', 'MTs', 'Swasta', 'Kusan Hilir'),
('MTSS NURUL JIHAD NW', 'MTs', 'Swasta', 'Sungai Loban'),
('MTSS NURUL WATHAN', 'MTs', 'Swasta', 'Mantewe'),
('MTSS RIADHUSSHALIHIN', 'MTs', 'Swasta', 'Satui'),
('MTSS SA AI ISTIQOMAH', 'MTs', 'Swasta', 'Mantewe'),
('MTSS SULLAMUL KHAIR', 'MTs', 'Swasta', 'Kusan Hulu'),
('MTSS SYARIF ALI', 'MTs', 'Swasta', 'Angsana'),
('MTs SYARIF ABBAS', 'MTs', 'Swasta', 'Batu Licin'),
('MTsN 1 TANAH BUMBU', 'MTs', 'Negeri', 'Kusan Hilir'),
('MTsN 2 TANAH BUMBU', 'MTs', 'Negeri', 'Kusan Hilir'),
('MTsN 3 TANAH BUMBU', 'MTs', 'Negeri', 'Satui'),
('MTsS NURUL AMIEN', 'MTs', 'Swasta', 'Kuranji'),
('MTsS NURUL HIDAYAH', 'MTs', 'Swasta', 'Simpang Empat'),
('SD 1 BATU BULAN', 'SD', 'Swasta', 'Kusan Hulu'),
('SD 2 TEMUNIH', 'SD', 'Swasta', 'Kusan Hulu'),
('SD 3 BAYANSARI', 'SD', 'Swasta', 'Angsana'),
('SD 3 BUKIT BARU', 'SD', 'Swasta', 'Satui'),
('SD 4 SEKAPUK', 'SD', 'Swasta', 'Satui'),
('SD BANGUN BENUA', 'SD', 'Swasta', 'Simpang Empat'),
('SD BINA BERSAMA', 'SD', 'Swasta', 'Satui'),
('SD ISLAM TERPADU AR RASYID', 'SD', 'Swasta', 'Batu Licin'),
('SD IT AN-NAHL', 'SD', 'Swasta', 'Angsana'),
('SD KATOLIK ST. VINCENT', 'SD', 'Swasta', 'Simpang Empat'),
('SD MANIARI', 'SD', 'Swasta', 'Mantewe'),
('SD MUHAMMADIYAH', 'SD', 'Swasta', 'Kusan Hilir'),
('SD MUHAMMADIYAH', 'SD', 'Swasta', 'Satui'),
('SD MUHAMMADIYAH', 'SD', 'Swasta', 'Simpang Empat'),
('SD NEGERI  BAROKAH', 'SD', 'Negeri', 'Simpang Empat'),
('SD NEGERI 1 BANJARSARI', 'SD', 'Negeri', 'Angsana'),
('SD NEGERI 1 BATU MERANTI', 'SD', 'Negeri', 'Sungai Loban'),
('SD NEGERI 1 BATUAH', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI 1 BATULICIN', 'SD', 'Negeri', 'Batu Licin'),
('SD NEGERI 1 BATULICIN IRIGASI', 'SD', 'Negeri', 'Karang Bintang'),
('SD NEGERI 1 BAYANSARI', 'SD', 'Negeri', 'Angsana'),
('SD NEGERI 1 BUKIT BARU', 'SD', 'Negeri', 'Satui'),
('SD NEGERI 1 BULUREJO', 'SD', 'Negeri', 'Mantewe'),
('SD NEGERI 1 DWI MARGA UTAMA', 'SD', 'Negeri', 'Sungai Loban'),
('SD NEGERI 1 GIRI MULIA', 'SD', 'Negeri', 'Kuranji'),
('SD NEGERI 1 HARAPAN MAJU', 'SD', 'Negeri', 'Karang Bintang'),
('SD NEGERI 1 KAMPUNG BARU', 'SD', 'Negeri', 'Simpang Empat'),
('SD NEGERI 1 KARANG INDAH', 'SD', 'Negeri', 'Angsana'),
('SD NEGERI 1 KOTA PAGATAN', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI 1 KUSAMBI', 'SD', 'Negeri', 'Batu Licin'),
('SD NEGERI 1 MANTEWE', 'SD', 'Negeri', 'Mantewe'),
('SD NEGERI 1 MANUNGGAL', 'SD', 'Negeri', 'Karang Bintang'),
('SD NEGERI 1 MANURUNG', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI 1 MARGA MULYA', 'SD', 'Negeri', 'Sungai Loban'),
('SD NEGERI 1 PASAR BARU', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI 1 PEMATANG ULIN', 'SD', 'Negeri', 'Karang Bintang'),
('SD NEGERI 1 REJOSARI', 'SD', 'Negeri', 'Mantewe'),
('SD NEGERI 1 SALIMURAN', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI 1 SARI MULYA', 'SD', 'Negeri', 'Sungai Loban'),
('SD NEGERI 1 SARI UTAMA', 'SD', 'Negeri', 'Sungai Loban'),
('SD NEGERI 1 SARIGADUNG', 'SD', 'Negeri', 'Simpang Empat'),
('SD NEGERI 1 SARIMULYA', 'SD', 'Negeri', 'Mantewe'),
('SD NEGERI 1 SATUI TIMUR', 'SD', 'Negeri', 'Satui'),
('SD NEGERI 1 SEKAPUK', 'SD', 'Negeri', 'Satui'),
('SD NEGERI 1 SEPAKAT', 'SD', 'Negeri', 'Mantewe'),
('SD NEGERI 1 SEPUNGGUR', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI 1 SUKADAMAI', 'SD', 'Negeri', 'Mantewe'),
('SD NEGERI 1 SUNGAI CUKA', 'SD', 'Negeri', 'Satui'),
('SD NEGERI 1 SUNGAI DANAU', 'SD', 'Negeri', 'Satui'),
('SD NEGERI 1 SUNGAI DUA', 'SD', 'Negeri', 'Simpang Empat'),
('SD NEGERI 1 TELUK KEPAYANG', 'SD', 'Negeri', 'Kusan Hulu'),
('SD NEGERI 1 TRI MULYA', 'SD', 'Negeri', 'Sungai Loban'),
('SD NEGERI 1 TUNGKARAN PANGERAN', 'SD', 'Negeri', 'Simpang Empat'),
('SD NEGERI 1 WONOREJO', 'SD', 'Negeri', 'Satui'),
('SD NEGERI 10 KAMPUNG BARU', 'SD', 'Negeri', 'Simpang Empat'),
('SD NEGERI 2 BANJARSARI', 'SD', 'Negeri', 'Angsana'),
('SD NEGERI 2 BATU MERANTI', 'SD', 'Negeri', 'Sungai Loban'),
('SD NEGERI 2 BATUAH', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI 2 BATULICIN', 'SD', 'Negeri', 'Batu Licin'),
('SD NEGERI 2 BATULICIN IRIGASI', 'SD', 'Negeri', 'Karang Bintang'),
('SD NEGERI 2 BAYANSARI', 'SD', 'Negeri', 'Angsana'),
('SD NEGERI 2 BULUREJO', 'SD', 'Negeri', 'Mantewe'),
('SD NEGERI 2 DWI MARGA UTAMA', 'SD', 'Negeri', 'Sungai Loban'),
('SD NEGERI 2 GIRI MULYA', 'SD', 'Negeri', 'Kuranji'),
('SD NEGERI 2 HARAPAN MAJU', 'SD', 'Negeri', 'Karang Bintang'),
('SD NEGERI 2 KAMPUNG BARU', 'SD', 'Negeri', 'Simpang Empat'),
('SD NEGERI 2 KARANG INDAH', 'SD', 'Negeri', 'Angsana'),
('SD NEGERI 2 KERSIK PUTIH', 'SD', 'Negeri', 'Batu Licin'),
('SD NEGERI 2 KUSAMBI', 'SD', 'Negeri', 'Batu Licin'),
('SD NEGERI 2 MANTEWE', 'SD', 'Negeri', 'Mantewe'),
('SD NEGERI 2 MANUNGGAL', 'SD', 'Negeri', 'Karang Bintang'),
('SD NEGERI 2 MANURUNG', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI 2 MARGA MULYA', 'SD', 'Negeri', 'Sungai Loban'),
('SD NEGERI 2 PASAR BARU', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI 2 PEMATANG ULIN', 'SD', 'Negeri', 'Karang Bintang'),
('SD NEGERI 2 SALIMURAN', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI 2 SARI MULYA', 'SD', 'Negeri', 'Sungai Loban'),
('SD NEGERI 2 SARI UTAMA', 'SD', 'Negeri', 'Sungai Loban'),
('SD NEGERI 2 SARIGADUNG', 'SD', 'Negeri', 'Simpang Empat'),
('SD NEGERI 2 SARIMULYA', 'SD', 'Negeri', 'Mantewe'),
('SD NEGERI 2 SATUI TIMUR', 'SD', 'Negeri', 'Satui'),
('SD NEGERI 2 SEKAPUK', 'SD', 'Negeri', 'Satui'),
('SD NEGERI 2 SEPUNGGUR', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI 2 SUNGAI CUKA', 'SD', 'Negeri', 'Satui'),
('SD NEGERI 2 SUNGAI DANAU', 'SD', 'Negeri', 'Satui'),
('SD NEGERI 2 SUNGAI DUA', 'SD', 'Negeri', 'Simpang Empat'),
('SD NEGERI 2 TELUK KEPAYANG', 'SD', 'Negeri', 'Kusan Hulu'),
('SD NEGERI 2 TRI MULYA', 'SD', 'Negeri', 'Sungai Loban'),
('SD NEGERI 2 TUNGKARAN PANGERAN', 'SD', 'Negeri', 'Simpang Empat'),
('SD NEGERI 3 BATUAH', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI 3 BATULICIN', 'SD', 'Negeri', 'Batu Licin'),
('SD NEGERI 3 KAMPUNG BARU', 'SD', 'Negeri', 'Simpang Empat'),
('SD NEGERI 3 PASAR BARU', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI 3 SARIGADUNG', 'SD', 'Negeri', 'Simpang Empat'),
('SD NEGERI 3 SEKAPUK', 'SD', 'Negeri', 'Satui'),
('SD NEGERI 3 SUNGAI DANAU', 'SD', 'Negeri', 'Satui'),
('SD NEGERI 3 TRI MULYA', 'SD', 'Negeri', 'Sungai Loban'),
('SD NEGERI 3 TUNGKARAN PANGERAN', 'SD', 'Negeri', 'Simpang Empat'),
('SD NEGERI 4 KAMPUNG BARU', 'SD', 'Negeri', 'Simpang Empat'),
('SD NEGERI 4 MANTEWE', 'SD', 'Negeri', 'Mantewe'),
('SD NEGERI 4 SUNGAI DANAU', 'SD', 'Negeri', 'Satui'),
('SD NEGERI 4 TUNGKARAN PANGERAN', 'SD', 'Negeri', 'Simpang Empat'),
('SD NEGERI 5 KAMPUNG BARU', 'SD', 'Negeri', 'Simpang Empat'),
('SD NEGERI 5 SUNGAI DANAU', 'SD', 'Negeri', 'Satui'),
('SD NEGERI 5 TUNGKARAN PANGERAN', 'SD', 'Negeri', 'Simpang Empat'),
('SD NEGERI 6 KAMPUNG BARU', 'SD', 'Negeri', 'Simpang Empat'),
('SD NEGERI 6 SUNGAI DANAU', 'SD', 'Negeri', 'Satui'),
('SD NEGERI 7 KAMPUNG BARU', 'SD', 'Negeri', 'Simpang Empat'),
('SD NEGERI 8 KAMPUNG BARU', 'SD', 'Negeri', 'Simpang Empat'),
('SD NEGERI 9 KAMPUNG BARU', 'SD', 'Negeri', 'Simpang Empat'),
('SD NEGERI ANGSANA', 'SD', 'Negeri', 'Angsana'),
('SD NEGERI ANJIR BARU', 'SD', 'Negeri', 'Kusan Hulu'),
('SD NEGERI BAKARANGAN', 'SD', 'Negeri', 'Kusan Hulu'),
('SD NEGERI BARUGELANG', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI BATU AMPAR', 'SD', 'Negeri', 'Simpang Empat'),
('SD NEGERI BATU BAHALANG', 'SD', 'Negeri', 'Batu Licin'),
('SD NEGERI BERINGIN', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI BETUNG', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI BINAWARA', 'SD', 'Negeri', 'Kusan Hulu'),
('SD NEGERI BUNATI', 'SD', 'Negeri', 'Angsana'),
('SD NEGERI DUKUH REJO', 'SD', 'Negeri', 'Mantewe'),
('SD NEGERI EMIL BARU', 'SD', 'Negeri', 'Mantewe'),
('SD NEGERI GUNTUNG', 'SD', 'Negeri', 'Kusan Hulu'),
('SD NEGERI INDRALOKA JAYA', 'SD', 'Negeri', 'Kuranji'),
('SD NEGERI JOMBANG', 'SD', 'Negeri', 'Satui'),
('SD NEGERI JUKU EJA', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI KAMPUNG BARU', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI KARANG BINTANG', 'SD', 'Negeri', 'Karang Bintang'),
('SD NEGERI KARANG INTAN', 'SD', 'Negeri', 'Kuranji'),
('SD NEGERI KARANG MULYA', 'SD', 'Negeri', 'Kusan Hulu'),
('SD NEGERI KARANG SARI', 'SD', 'Negeri', 'Kusan Hulu'),
('SD NEGERI KARYA BAKTI', 'SD', 'Negeri', 'Mantewe'),
('SD NEGERI KERSIK PUTIH', 'SD', 'Negeri', 'Batu Licin'),
('SD NEGERI KERTA BUWANA', 'SD', 'Negeri', 'Sungai Loban'),
('SD NEGERI KUNDUR', 'SD', 'Negeri', 'Kusan Hulu'),
('SD NEGERI KURANJI', 'SD', 'Negeri', 'Kuranji'),
('SD NEGERI LASUNG', 'SD', 'Negeri', 'Kusan Hulu'),
('SD NEGERI MANUNTUNG', 'SD', 'Negeri', 'Kusan Hulu'),
('SD NEGERI MEKAR SARI', 'SD', 'Negeri', 'Simpang Empat'),
('SD NEGERI MUARA PAGATAN TENGAH', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI MUARA PAGATAN UJUNG', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI MUDALANG', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI MUSTIKA', 'SD', 'Negeri', 'Kuranji'),
('SD NEGERI PACAKAN', 'SD', 'Negeri', 'Kusan Hulu'),
('SD NEGERI PAKATELU', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI PANDANSARI', 'SD', 'Negeri', 'Karang Bintang'),
('SD NEGERI PENYOLONGAN', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI PONDOK BUTUN', 'SD', 'Negeri', 'Batu Licin'),
('SD NEGERI PULAU SATU', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI PULAU TANJUNG', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI PURWODADI', 'SD', 'Negeri', 'Angsana'),
('SD NEGERI RANTAU PANJANG', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI REJOWINANGUN', 'SD', 'Negeri', 'Karang Bintang'),
('SD NEGERI RINGKIT', 'SD', 'Negeri', 'Kusan Hulu'),
('SD NEGERI SARDANGAN', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI SARING SUNGAI BINJAI', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI SARING SUNGAI BUBU', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI SATIUNG', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI SATIUNG SALIMURAN', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI SEBAMBAN BARU', 'SD', 'Negeri', 'Sungai Loban'),
('SD NEGERI SEBAMBAN LAMA', 'SD', 'Negeri', 'Sungai Loban'),
('SD NEGERI SEGUMBANG', 'SD', 'Negeri', 'Batu Licin'),
('SD NEGERI SETARAP', 'SD', 'Negeri', 'Satui'),
('SD NEGERI SIDOMULYO', 'SD', 'Negeri', 'Mantewe'),
('SD NEGERI SUMBER ARUM', 'SD', 'Negeri', 'Satui'),
('SD NEGERI SUMBER BARU', 'SD', 'Negeri', 'Angsana'),
('SD NEGERI SUMBER MAKMUR', 'SD', 'Negeri', 'Satui'),
('SD NEGERI SUNGAI DUA LAUT', 'SD', 'Negeri', 'Sungai Loban'),
('SD NEGERI SUNGAI LEMBU', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI SUNGAI LOBAN', 'SD', 'Negeri', 'Sungai Loban'),
('SD NEGERI SUNGAI SELILAU', 'SD', 'Negeri', 'Karang Bintang'),
('SD NEGERI TANETE', 'SD', 'Negeri', 'Kusan Hilir'),
('SD NEGERI TAPUS', 'SD', 'Negeri', 'Kusan Hulu'),
('SD NEGERI TEGALSARI', 'SD', 'Negeri', 'Satui'),
('SD NEGERI TIBARAU PANJANG', 'SD', 'Negeri', 'Kusan Hulu'),
('SD NEGERI TRI MARTANI', 'SD', 'Negeri', 'Sungai Loban'),
('SD NEGERI TUNAS MULYA', 'SD', 'Negeri', 'Kusan Hulu'),
('SD NEGERI WARINGIN TUNGGAL', 'SD', 'Negeri', 'Kuranji'),
('SD NEGERI WONOREJO', 'SD', 'Negeri', 'Kusan Hulu'),
('SD Negeri 7 Sungai Danau', 'SD', 'Negeri', 'Satui'),
('SD RAJAWALI', 'SD', 'Swasta', 'Kusan Hulu'),
('SD SAMBA', 'SD', 'Swasta', 'Kusan Hilir'),
('SDIT AL-FATH', 'SD', 'Swasta', 'Batu Licin'),
('SDIT DHIA EL WIDAD', 'SD', 'Swasta', 'Sungai Loban'),
('SDN 2 BUKIT BARU', 'SD', 'Negeri', 'Satui'),
('SDN 3 MANTEWE', 'SD', 'Negeri', 'Mantewe'),
('SDN BATU HARANG', 'SD', 'Negeri', 'Mantewe'),
('SDN DERMAGA', 'SD', 'Negeri', 'Sungai Loban'),
('SDN MANGKALAPI', 'SD', 'Negeri', 'Kusan Hulu'),
('SDN PENYIPUTAN', 'SD', 'Negeri', 'Sungai Loban'),
('SDN SUNGAI TAJUR', 'SD', 'Negeri', 'Simpang Empat'),
('SDN Satui Barat', 'SD', 'Negeri', 'Satui'),
('SDN TUNAS NELAYAN', 'SD', 'Negeri', 'Simpang Empat'),
('SDTQ DARUL ILMI', 'SD', 'Swasta', 'Karang Bintang'),
('SMA IT Al Asmaul Husna', 'SMA', 'Swasta', 'Simpang Empat'),
('SMAIT Plus Ar - Rasyid', 'SMA', 'Swasta', 'Batu Licin'),
('SMAN 1 ANGSANA', 'SMA', 'Negeri', 'Angsana'),
('SMAN 1 KARANG BINTANG', 'SMA', 'Negeri', 'Karang Bintang'),
('SMAN 1 KUSAN HILIR', 'SMA', 'Negeri', 'Kusan Hilir'),
('SMAN 1 KUSAN HULU', 'SMA', 'Negeri', 'Kusan Hulu'),
('SMAN 1 Kuranji', 'SMA', 'Negeri', 'Kuranji'),
('SMAN 1 MANTEWE', 'SMA', 'Negeri', 'Mantewe'),
('SMAN 1 SATUI', 'SMA', 'Negeri', 'Satui'),
('SMAN 1 SIMPANG EMPAT', 'SMA', 'Negeri', 'Simpang Empat'),
('SMAN 1 SUNGAI LOBAN', 'SMA', 'Negeri', 'Sungai Loban'),
('SMAN 2 SATUI', 'SMA', 'Negeri', 'Satui'),
('SMAN 2 Simpang Empat', 'SMA', 'Negeri', 'Simpang Empat'),
('SMAS Nusantara', 'SMA', 'Swasta', 'Karang Bintang'),
('SMK Negeri 1 Kusan Hulu', 'SMK', 'Negeri', 'Kusan Hulu'),
('SMKN 1 KUSAN HILIR', 'SMK', 'Negeri', 'Kusan Hilir'),
('SMKN 1 SATUI', 'SMK', 'Negeri', 'Satui'),
('SMKN 1 SIMPANG EMPAT', 'SMK', 'Negeri', 'Simpang Empat'),
('SMKN 1 SUNGAI LOBAN', 'SMK', 'Negeri', 'Sungai Loban'),
('SMKN 2 SIMPANG EMPAT', 'SMK', 'Negeri', 'Simpang Empat'),
('SMKN 2 Satui', 'SMK', 'Negeri', 'Satui'),
('SMKS AL MADANI TERPADU', 'SMK', 'Swasta', 'Karang Bintang'),
('SMKS ALHIDAYAH', 'SMK', 'Swasta', 'Batu Licin'),
('SMKS BANGUN BANUA', 'SMK', 'Swasta', 'Simpang Empat'),
('SMKS DDI', 'SMK', 'Swasta', 'Batu Licin'),
('SMKS INSAN LUHUR NUSANTARA', 'SMK', 'Swasta', 'Angsana'),
('SMKS Islam Raudhatul Jannah', 'SMK', 'Swasta', 'Sungai Loban'),
('SMKS KODECO', 'SMK', 'Swasta', 'Simpang Empat'),
('SMKS Muhammadiyah Kusan Hilir', 'SMK', 'Swasta', 'Kusan Hilir'),
('SMKS Muhammadiyah Satui', 'SMK', 'Swasta', 'Satui'),
('SMKS TUNAS BANGSA', 'SMK', 'Swasta', 'Batu Licin'),
('SMKS Teluk Kepayang', 'SMK', 'Swasta', 'Kusan Hulu'),
('SMP BANGUN BENUA', 'SMP', 'Swasta', 'Simpang Empat'),
('SMP Gunung Sari Estate', 'SMP', 'Swasta', 'Angsana'),
('SMP ISLAM TERPADU AR RASYID', 'SMP', 'Swasta', 'Batu Licin'),
('SMP IT AL-ASMAUL HUSNA', 'SMP', 'Swasta', 'Simpang Empat'),
('SMP IT Darul Ijabah', 'SMP', 'Swasta', 'Batu Licin'),
('SMP Islam Raudhatur Rahmah', 'SMP', 'Swasta', 'Sungai Loban'),
('SMP KODECO', 'SMP', 'Swasta', 'Simpang Empat'),
('SMP MUHAMMADIYAH', 'SMP', 'Swasta', 'Kusan Hilir'),
('SMP MUHAMMADIYAH SIMPANG EMPAT', 'SMP', 'Swasta', 'Simpang Empat'),
('SMP NEGERI 1 ANGSANA', 'SMP', 'Negeri', 'Angsana'),
('SMP NEGERI 1 BATULICIN', 'SMP', 'Negeri', 'Batu Licin'),
('SMP NEGERI 1 KARANG BINTANG', 'SMP', 'Negeri', 'Karang Bintang'),
('SMP NEGERI 1 KURANJI', 'SMP', 'Negeri', 'Kuranji'),
('SMP NEGERI 1 KUSAN HILIR', 'SMP', 'Negeri', 'Kusan Hilir'),
('SMP NEGERI 1 KUSAN HULU', 'SMP', 'Negeri', 'Kusan Hulu'),
('SMP NEGERI 1 MANTEWE', 'SMP', 'Negeri', 'Mantewe'),
('SMP NEGERI 1 SATUI', 'SMP', 'Negeri', 'Satui'),
('SMP NEGERI 1 SIMPANG EMPAT', 'SMP', 'Negeri', 'Simpang Empat'),
('SMP NEGERI 1 SUNGAI LOBAN', 'SMP', 'Negeri', 'Sungai Loban'),
('SMP NEGERI 2 ANGSANA', 'SMP', 'Negeri', 'Angsana'),
('SMP NEGERI 2 BATULICIN', 'SMP', 'Negeri', 'Batu Licin'),
('SMP NEGERI 2 KARANG BINTANG', 'SMP', 'Negeri', 'Karang Bintang'),
('SMP NEGERI 2 KUSAN HILIR', 'SMP', 'Negeri', 'Kusan Hilir'),
('SMP NEGERI 2 KUSAN HULU', 'SMP', 'Negeri', 'Kusan Hulu'),
('SMP NEGERI 2 MANTEWE', 'SMP', 'Negeri', 'Mantewe'),
('SMP NEGERI 2 SATU ATAP KURANJI', 'SMP', 'Negeri', 'Kuranji'),
('SMP NEGERI 2 SATUI', 'SMP', 'Negeri', 'Satui'),
('SMP NEGERI 2 SIMPANG EMPAT', 'SMP', 'Negeri', 'Simpang Empat'),
('SMP NEGERI 2 SUNGAI LOBAN', 'SMP', 'Negeri', 'Sungai Loban'),
('SMP NEGERI 3 KARANG BINTANG', 'SMP', 'Negeri', 'Karang Bintang'),
('SMP NEGERI 3 KUSAN HILIR', 'SMP', 'Negeri', 'Kusan Hilir'),
('SMP NEGERI 3 KUSAN HULU', 'SMP', 'Negeri', 'Kusan Hulu'),
('SMP NEGERI 3 SATU ATAP BATULICIN', 'SMP', 'Negeri', 'Batu Licin'),
('SMP NEGERI 3 SATU ATAP SATUI', 'SMP', 'Negeri', 'Satui'),
('SMP NEGERI 3 SUNGAI LOBAN', 'SMP', 'Negeri', 'Sungai Loban'),
('SMP NEGERI 4 BATULICIN', 'SMP', 'Negeri', 'Batu Licin'),
('SMP NEGERI 4 SATU ATAP KARANG BINTANG', 'SMP', 'Negeri', 'Karang Bintang'),
('SMP NEGERI 4 SATU ATAP KUSAN HILIR', 'SMP', 'Negeri', 'Kusan Hilir'),
('SMP NEGERI 4 SATU ATAP MANTEWE', 'SMP', 'Negeri', 'Mantewe'),
('SMP NEGERI 4 SATUI', 'SMP', 'Negeri', 'Satui'),
('SMP NEGERI 4 SUNGAI LOBAN', 'SMP', 'Negeri', 'Sungai Loban'),
('SMP NEGERI 5 KUSAN HILIR', 'SMP', 'Negeri', 'Kusan Hilir'),
('SMP NEGERI 5 SATU ATAP MANTEWE', 'SMP', 'Negeri', 'Mantewe'),
('SMP NEGERI 5 SATU ATAP SATUI', 'SMP', 'Negeri', 'Satui'),
('SMP NEGERI 6 SATU ATAP KUSAN HILIR', 'SMP', 'Negeri', 'Kusan Hilir'),
('SMP NEGERI 6 SATUI', 'SMP', 'Negeri', 'Satui'),
('SMP NEGERI 7 KUSAN HILIR', 'SMP', 'Negeri', 'Kusan Hilir'),
('SMP NEGERI 8 SATU ATAP KUSAN HILIR', 'SMP', 'Negeri', 'Kusan Hilir'),
('SMP NEGERI 9 SATU ATAP SATUI', 'SMP', 'Negeri', 'Satui'),
('SMP Negeri 10 Satui', 'SMP', 'Negeri', 'Satui'),
('SMP Negeri 4 Simpang Empat', 'SMP', 'Negeri', 'Simpang Empat'),
('SMP Negeri 5 Simpang Empat', 'SMP', 'Negeri', 'Simpang Empat'),
('SMPN 3 SATAP SIMPANG EMPAT', 'SMP', 'Negeri', 'Simpang Empat'),
('SMPN 3 SATU ATAP ANGSANA', 'SMP', 'Negeri', 'Angsana'),
('SMPN 4 SATU ATAP KUSAN HULU', 'SMP', 'Negeri', 'Kusan Hulu'),
('SMPN 6 SATU ATAP MANTEWE', 'SMP', 'Negeri', 'Mantewe'),
('SMPN 7 SATAP MANTEWE', 'SMP', 'Negeri', 'Mantewe'),
('SMPN 7 SATU ATAP SATUI', 'SMP', 'Negeri', 'Satui'),
('SMPN 8 SATAP MANTEWE', 'SMP', 'Negeri', 'Mantewe'),
('SMPN 8 SATAP SATUI', 'SMP', 'Negeri', 'Satui'),
('SMPN 9 SATAP MANTEWE', 'SMP', 'Negeri', 'Mantewe');
;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DELETE FROM renjana_schools;
-- +goose StatementEnd
