// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: achievements.sql

package queries

import (
	"context"
)

const getAchievementsByYear = `-- name: GetAchievementsByYear :many
SELECT id, year, metric_key, metric_name, value, unit, target, display_order, icon, icon_color, created_at
FROM renjana_achievements
WHERE year = ?
ORDER BY display_order
`

func (q *Queries) GetAchievementsByYear(ctx context.Context, year int64) ([]RenjanaAchievement, error) {
	rows, err := q.db.QueryContext(ctx, getAchievementsByYear, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenjanaAchievement
	for rows.Next() {
		var i RenjanaAchievement
		if err := rows.Scan(
			&i.ID,
			&i.Year,
			&i.MetricKey,
			&i.MetricName,
			&i.Value,
			&i.Unit,
			&i.Target,
			&i.DisplayOrder,
			&i.Icon,
			&i.IconColor,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
