// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: achievements.sql

package queries

import (
	"context"
)

const getAchievements = `-- name: GetAchievements :many
SELECT id, metric_name, value, unit, display_order, created_at
FROM renjana_achievements
ORDER BY display_order
`

func (q *Queries) GetAchievements(ctx context.Context) ([]RenjanaAchievement, error) {
	rows, err := q.db.QueryContext(ctx, getAchievements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenjanaAchievement
	for rows.Next() {
		var i RenjanaAchievement
		if err := rows.Scan(
			&i.ID,
			&i.MetricName,
			&i.Value,
			&i.Unit,
			&i.DisplayOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAchievement = `-- name: UpdateAchievement :execrows
UPDATE renjana_achievements
SET metric_name = ?, value = ?, unit = ?
WHERE id = ?
`

type UpdateAchievementParams struct {
	MetricName string  `json:"metric_name"`
	Value      float64 `json:"value"`
	Unit       string  `json:"unit"`
	ID         int64   `json:"id"`
}

func (q *Queries) UpdateAchievement(ctx context.Context, arg UpdateAchievementParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAchievement,
		arg.MetricName,
		arg.Value,
		arg.Unit,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
