// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity_types.sql

package queries

import (
	"context"
)

const getAllActivityTypes = `-- name: GetAllActivityTypes :many
SELECT id, name, color, icon, display_order, is_active, created_at
FROM renjana_activity_types
WHERE is_active = 1
ORDER BY display_order
`

func (q *Queries) GetAllActivityTypes(ctx context.Context) ([]RenjanaActivityType, error) {
	rows, err := q.db.QueryContext(ctx, getAllActivityTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenjanaActivityType
	for rows.Next() {
		var i RenjanaActivityType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Icon,
			&i.DisplayOrder,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
