// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activities.sql

package queries

import (
	"context"
	"time"
)

const countActivitiesByDistrict = `-- name: CountActivitiesByDistrict :many
SELECT
    d.id AS district_id,
    d.name AS district_name,
    COUNT(a.id) AS activity_count
FROM renjana_districts d
LEFT JOIN renjana_activities a ON a.district_id = d.id
GROUP BY d.id, d.name
ORDER BY activity_count DESC, d.name
`

type CountActivitiesByDistrictRow struct {
	DistrictID    int64
	DistrictName  string
	ActivityCount int64
}

func (q *Queries) CountActivitiesByDistrict(ctx context.Context) ([]CountActivitiesByDistrictRow, error) {
	rows, err := q.db.QueryContext(ctx, countActivitiesByDistrict)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountActivitiesByDistrictRow
	for rows.Next() {
		var i CountActivitiesByDistrictRow
		if err := rows.Scan(&i.DistrictID, &i.DistrictName, &i.ActivityCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countActivitiesByType = `-- name: CountActivitiesByType :many
SELECT
    t.id AS type_id,
    t.name AS type_name,
    t.color,
    t.icon,
    COUNT(a.id) AS activity_count
FROM renjana_activity_types t
LEFT JOIN renjana_activities a ON a.type_id = t.id
WHERE t.is_active = 1
GROUP BY t.id, t.name, t.color, t.icon
ORDER BY activity_count DESC, t.display_order
`

type CountActivitiesByTypeRow struct {
	TypeID        int64
	TypeName      string
	Color         string
	Icon          string
	ActivityCount int64
}

func (q *Queries) CountActivitiesByType(ctx context.Context) ([]CountActivitiesByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, countActivitiesByType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountActivitiesByTypeRow
	for rows.Next() {
		var i CountActivitiesByTypeRow
		if err := rows.Scan(
			&i.TypeID,
			&i.TypeName,
			&i.Color,
			&i.Icon,
			&i.ActivityCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAllActivities = `-- name: CountAllActivities :one
SELECT COUNT(*) AS total
FROM renjana_activities
`

func (q *Queries) CountAllActivities(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllActivities)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countAllActivitiesPreviousMonth = `-- name: CountAllActivitiesPreviousMonth :one
SELECT COUNT(*) AS total
FROM renjana_activities
WHERE date < date('now', '-30 days')
`

// Approximation: total minus this-month's count
func (q *Queries) CountAllActivitiesPreviousMonth(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllActivitiesPreviousMonth)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getUpcomingActivities = `-- name: GetUpcomingActivities :many
SELECT
    a.id,
    a.title,
    a.type_id,
    t.name AS type_name,
    t.color AS type_color,
    t.icon AS type_icon,
    a.district_id,
    d.name AS district_name,
    a.location,
    a.date,
    a.time,
    a.status
FROM renjana_activities a
JOIN renjana_activity_types t ON t.id = a.type_id
JOIN renjana_districts d ON d.id = a.district_id
WHERE a.status = 'akan_datang'
ORDER BY a.date ASC, a.time ASC
LIMIT ?
`

type GetUpcomingActivitiesRow struct {
	ID           int64
	Title        string
	TypeID       int64
	TypeName     string
	TypeColor    string
	TypeIcon     string
	DistrictID   int64
	DistrictName string
	Location     string
	Date         time.Time
	Time         string
	Status       string
}

func (q *Queries) GetUpcomingActivities(ctx context.Context, limit int64) ([]GetUpcomingActivitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUpcomingActivities, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUpcomingActivitiesRow
	for rows.Next() {
		var i GetUpcomingActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TypeID,
			&i.TypeName,
			&i.TypeColor,
			&i.TypeIcon,
			&i.DistrictID,
			&i.DistrictName,
			&i.Location,
			&i.Date,
			&i.Time,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
