// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: announcements.sql

package queries

import (
	"context"
)

const getLatestPublishedAnnouncement = `-- name: GetLatestPublishedAnnouncement :one
SELECT id, title, content, published_at, is_published, created_at
FROM renjana_announcements
WHERE is_published = 1
ORDER BY published_at DESC
LIMIT 1
`

func (q *Queries) GetLatestPublishedAnnouncement(ctx context.Context) (RenjanaAnnouncement, error) {
	row := q.db.QueryRowContext(ctx, getLatestPublishedAnnouncement)
	var i RenjanaAnnouncement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.PublishedAt,
		&i.IsPublished,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestPublishedAnnouncements = `-- name: GetLatestPublishedAnnouncements :many
SELECT id, title, content, published_at, is_published, created_at
FROM renjana_announcements
WHERE is_published = 1
ORDER BY published_at DESC
LIMIT ?
`

func (q *Queries) GetLatestPublishedAnnouncements(ctx context.Context, limit int64) ([]RenjanaAnnouncement, error) {
	rows, err := q.db.QueryContext(ctx, getLatestPublishedAnnouncements, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenjanaAnnouncement
	for rows.Next() {
		var i RenjanaAnnouncement
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.PublishedAt,
			&i.IsPublished,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
