// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: complaints.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const addComplaintMessage = `-- name: AddComplaintMessage :one
INSERT INTO renjana_complaint_messages (complaint_id, sender_type, sender_name, message)
VALUES (?1, ?2, ?3, ?4)
RETURNING id, complaint_id, sender_type, sender_name, message, created_at
`

type AddComplaintMessageParams struct {
	ComplaintID int64  `json:"complaint_id"`
	SenderType  string `json:"sender_type"`
	SenderName  string `json:"sender_name"`
	Message     string `json:"message"`
}

func (q *Queries) AddComplaintMessage(ctx context.Context, arg AddComplaintMessageParams) (RenjanaComplaintMessage, error) {
	row := q.db.QueryRowContext(ctx, addComplaintMessage,
		arg.ComplaintID,
		arg.SenderType,
		arg.SenderName,
		arg.Message,
	)
	var i RenjanaComplaintMessage
	err := row.Scan(
		&i.ID,
		&i.ComplaintID,
		&i.SenderType,
		&i.SenderName,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const countComplaints = `-- name: CountComplaints :one
SELECT COUNT(*) AS total
FROM renjana_complaints
`

func (q *Queries) CountComplaints(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countComplaints)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countComplaintsByCategory = `-- name: CountComplaintsByCategory :many
SELECT category, COUNT(*) AS count
FROM renjana_complaints
GROUP BY category
ORDER BY count DESC
`

type CountComplaintsByCategoryRow struct {
	Category string `json:"category"`
	Count    int64  `json:"count"`
}

func (q *Queries) CountComplaintsByCategory(ctx context.Context) ([]CountComplaintsByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, countComplaintsByCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountComplaintsByCategoryRow
	for rows.Next() {
		var i CountComplaintsByCategoryRow
		if err := rows.Scan(&i.Category, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countComplaintsByMonth = `-- name: CountComplaintsByMonth :many
SELECT strftime('%Y-%m', created_at) AS month, COUNT(*) AS count
FROM renjana_complaints
GROUP BY month
ORDER BY month DESC
LIMIT 12
`

type CountComplaintsByMonthRow struct {
	Month interface{} `json:"month"`
	Count int64       `json:"count"`
}

func (q *Queries) CountComplaintsByMonth(ctx context.Context) ([]CountComplaintsByMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, countComplaintsByMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountComplaintsByMonthRow
	for rows.Next() {
		var i CountComplaintsByMonthRow
		if err := rows.Scan(&i.Month, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countResolvedComplaints = `-- name: CountResolvedComplaints :one
SELECT COUNT(*) AS total
FROM renjana_complaints
WHERE status = 'resolved'
`

func (q *Queries) CountResolvedComplaints(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countResolvedComplaints)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createComplaint = `-- name: CreateComplaint :one
INSERT INTO renjana_complaints (name, email, phone, category, message, token)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
RETURNING id, name, email, phone, category, message, status, response, responded_by, responded_at, created_at, token
`

type CreateComplaintParams struct {
	Name     string         `json:"name"`
	Email    string         `json:"email"`
	Phone    sql.NullString `json:"phone"`
	Category string         `json:"category"`
	Message  string         `json:"message"`
	Token    sql.NullString `json:"token"`
}

func (q *Queries) CreateComplaint(ctx context.Context, arg CreateComplaintParams) (RenjanaComplaint, error) {
	row := q.db.QueryRowContext(ctx, createComplaint,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Category,
		arg.Message,
		arg.Token,
	)
	var i RenjanaComplaint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Category,
		&i.Message,
		&i.Status,
		&i.Response,
		&i.RespondedBy,
		&i.RespondedAt,
		&i.CreatedAt,
		&i.Token,
	)
	return i, err
}

const deleteComplaint = `-- name: DeleteComplaint :exec
DELETE FROM renjana_complaints WHERE id = ?
`

func (q *Queries) DeleteComplaint(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteComplaint, id)
	return err
}

const getComplaintByID = `-- name: GetComplaintByID :one
SELECT id, name, email, phone, category, message, status, response, responded_by, responded_at, created_at, token
FROM renjana_complaints
WHERE id = ?
`

func (q *Queries) GetComplaintByID(ctx context.Context, id int64) (RenjanaComplaint, error) {
	row := q.db.QueryRowContext(ctx, getComplaintByID, id)
	var i RenjanaComplaint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Category,
		&i.Message,
		&i.Status,
		&i.Response,
		&i.RespondedBy,
		&i.RespondedAt,
		&i.CreatedAt,
		&i.Token,
	)
	return i, err
}

const getComplaintByToken = `-- name: GetComplaintByToken :one
SELECT id, name, email, phone, category, message, status, response, responded_by, responded_at, created_at, token
FROM renjana_complaints
WHERE token = ?
`

func (q *Queries) GetComplaintByToken(ctx context.Context, token sql.NullString) (RenjanaComplaint, error) {
	row := q.db.QueryRowContext(ctx, getComplaintByToken, token)
	var i RenjanaComplaint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Category,
		&i.Message,
		&i.Status,
		&i.Response,
		&i.RespondedBy,
		&i.RespondedAt,
		&i.CreatedAt,
		&i.Token,
	)
	return i, err
}

const getComplaintStats = `-- name: GetComplaintStats :one
SELECT
    COUNT(*) AS total,
    SUM(CASE WHEN status = 'pending' THEN 1 ELSE 0 END) AS pending,
    SUM(CASE WHEN status = 'processed' THEN 1 ELSE 0 END) AS processed,
    SUM(CASE WHEN status = 'resolved' THEN 1 ELSE 0 END) AS resolved
FROM renjana_complaints
`

type GetComplaintStatsRow struct {
	Total     int64           `json:"total"`
	Pending   sql.NullFloat64 `json:"pending"`
	Processed sql.NullFloat64 `json:"processed"`
	Resolved  sql.NullFloat64 `json:"resolved"`
}

func (q *Queries) GetComplaintStats(ctx context.Context) (GetComplaintStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getComplaintStats)
	var i GetComplaintStatsRow
	err := row.Scan(
		&i.Total,
		&i.Pending,
		&i.Processed,
		&i.Resolved,
	)
	return i, err
}

const getLatestMessagesForComplaints = `-- name: GetLatestMessagesForComplaints :many
SELECT m.complaint_id, m.sender_type, m.sender_name, m.message, m.created_at
FROM renjana_complaint_messages m
WHERE m.id IN (
    SELECT MAX(m2.id)
    FROM renjana_complaint_messages m2
    GROUP BY m2.complaint_id
)
`

type GetLatestMessagesForComplaintsRow struct {
	ComplaintID int64     `json:"complaint_id"`
	SenderType  string    `json:"sender_type"`
	SenderName  string    `json:"sender_name"`
	Message     string    `json:"message"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) GetLatestMessagesForComplaints(ctx context.Context) ([]GetLatestMessagesForComplaintsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLatestMessagesForComplaints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestMessagesForComplaintsRow
	for rows.Next() {
		var i GetLatestMessagesForComplaintsRow
		if err := rows.Scan(
			&i.ComplaintID,
			&i.SenderType,
			&i.SenderName,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResponseTimeStats = `-- name: GetResponseTimeStats :one
SELECT
    COUNT(*) AS total_resolved,
    ROUND(AVG(julianday(responded_at) - julianday(created_at)), 1) AS avg_response_days
FROM renjana_complaints
WHERE status = 'resolved' AND responded_at IS NOT NULL
`

type GetResponseTimeStatsRow struct {
	TotalResolved   int64   `json:"total_resolved"`
	AvgResponseDays float64 `json:"avg_response_days"`
}

func (q *Queries) GetResponseTimeStats(ctx context.Context) (GetResponseTimeStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getResponseTimeStats)
	var i GetResponseTimeStatsRow
	err := row.Scan(&i.TotalResolved, &i.AvgResponseDays)
	return i, err
}

const listComplaintMessages = `-- name: ListComplaintMessages :many
SELECT id, complaint_id, sender_type, sender_name, message, created_at
FROM renjana_complaint_messages
WHERE complaint_id = ?1
ORDER BY created_at ASC
`

func (q *Queries) ListComplaintMessages(ctx context.Context, complaintID int64) ([]RenjanaComplaintMessage, error) {
	rows, err := q.db.QueryContext(ctx, listComplaintMessages, complaintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenjanaComplaintMessage
	for rows.Next() {
		var i RenjanaComplaintMessage
		if err := rows.Scan(
			&i.ID,
			&i.ComplaintID,
			&i.SenderType,
			&i.SenderName,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComplaintsPaginated = `-- name: ListComplaintsPaginated :many
SELECT id, name, email, phone, category, message, status, response, responded_by, responded_at, created_at, token
FROM renjana_complaints
ORDER BY created_at DESC
LIMIT ?1 OFFSET ?2
`

type ListComplaintsPaginatedParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListComplaintsPaginated(ctx context.Context, arg ListComplaintsPaginatedParams) ([]RenjanaComplaint, error) {
	rows, err := q.db.QueryContext(ctx, listComplaintsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenjanaComplaint
	for rows.Next() {
		var i RenjanaComplaint
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Category,
			&i.Message,
			&i.Status,
			&i.Response,
			&i.RespondedBy,
			&i.RespondedAt,
			&i.CreatedAt,
			&i.Token,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResolvedComplaints = `-- name: ListResolvedComplaints :many
SELECT id, name, email, phone, category, message, status, response, responded_by, responded_at, created_at, token
FROM renjana_complaints
WHERE status = 'resolved'
ORDER BY responded_at DESC
LIMIT ?1 OFFSET ?2
`

type ListResolvedComplaintsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListResolvedComplaints(ctx context.Context, arg ListResolvedComplaintsParams) ([]RenjanaComplaint, error) {
	rows, err := q.db.QueryContext(ctx, listResolvedComplaints, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenjanaComplaint
	for rows.Next() {
		var i RenjanaComplaint
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Category,
			&i.Message,
			&i.Status,
			&i.Response,
			&i.RespondedBy,
			&i.RespondedAt,
			&i.CreatedAt,
			&i.Token,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveComplaint = `-- name: ResolveComplaint :one
UPDATE renjana_complaints
SET status = 'resolved', responded_at = CURRENT_TIMESTAMP
WHERE id = ?1
RETURNING id, name, email, phone, category, message, status, response, responded_by, responded_at, created_at, token
`

func (q *Queries) ResolveComplaint(ctx context.Context, id int64) (RenjanaComplaint, error) {
	row := q.db.QueryRowContext(ctx, resolveComplaint, id)
	var i RenjanaComplaint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Category,
		&i.Message,
		&i.Status,
		&i.Response,
		&i.RespondedBy,
		&i.RespondedAt,
		&i.CreatedAt,
		&i.Token,
	)
	return i, err
}

const updateComplaintStatus = `-- name: UpdateComplaintStatus :one
UPDATE renjana_complaints
SET status = ?2, response = ?3, responded_by = ?4, responded_at = CURRENT_TIMESTAMP
WHERE id = ?1
RETURNING id, name, email, phone, category, message, status, response, responded_by, responded_at, created_at, token
`

type UpdateComplaintStatusParams struct {
	ID          int64          `json:"id"`
	Status      string         `json:"status"`
	Response    sql.NullString `json:"response"`
	RespondedBy sql.NullInt64  `json:"responded_by"`
}

func (q *Queries) UpdateComplaintStatus(ctx context.Context, arg UpdateComplaintStatusParams) (RenjanaComplaint, error) {
	row := q.db.QueryRowContext(ctx, updateComplaintStatus,
		arg.ID,
		arg.Status,
		arg.Response,
		arg.RespondedBy,
	)
	var i RenjanaComplaint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Category,
		&i.Message,
		&i.Status,
		&i.Response,
		&i.RespondedBy,
		&i.RespondedAt,
		&i.CreatedAt,
		&i.Token,
	)
	return i, err
}
