// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const countContactsFiltered = `-- name: CountContactsFiltered :one
SELECT COUNT(*) AS total
FROM renjana_contacts c
JOIN renjana_districts d ON d.id = c.district_id
WHERE (?1 IS NULL OR ?1 = ''
       OR c.name LIKE '%' || ?1 || '%'
       OR c.role LIKE '%' || ?1 || '%'
       OR d.name LIKE '%' || ?1 || '%')
  AND (?2 = 0 OR c.district_id = ?2)
`

type CountContactsFilteredParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) CountContactsFiltered(ctx context.Context, arg CountContactsFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countContactsFiltered, arg.Column1, arg.Column2)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createContact = `-- name: CreateContact :one
INSERT INTO renjana_contacts (district_id, name, role, phone, email, is_active)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateContactParams struct {
	DistrictID int64          `json:"district_id"`
	Name       string         `json:"name"`
	Role       string         `json:"role"`
	Phone      sql.NullString `json:"phone"`
	Email      sql.NullString `json:"email"`
	IsActive   bool           `json:"is_active"`
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createContact,
		arg.DistrictID,
		arg.Name,
		arg.Role,
		arg.Phone,
		arg.Email,
		arg.IsActive,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteContact = `-- name: DeleteContact :execrows
DELETE FROM renjana_contacts WHERE id = ?
`

func (q *Queries) DeleteContact(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteContact, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getContactByID = `-- name: GetContactByID :one
SELECT
    c.id, c.district_id, d.name AS district_name, c.name, c.role,
    c.phone, c.email, c.is_active, c.created_at
FROM renjana_contacts c
JOIN renjana_districts d ON d.id = c.district_id
WHERE c.id = ?
`

type GetContactByIDRow struct {
	ID           int64          `json:"id"`
	DistrictID   int64          `json:"district_id"`
	DistrictName string         `json:"district_name"`
	Name         string         `json:"name"`
	Role         string         `json:"role"`
	Phone        sql.NullString `json:"phone"`
	Email        sql.NullString `json:"email"`
	IsActive     bool           `json:"is_active"`
	CreatedAt    time.Time      `json:"created_at"`
}

func (q *Queries) GetContactByID(ctx context.Context, id int64) (GetContactByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getContactByID, id)
	var i GetContactByIDRow
	err := row.Scan(
		&i.ID,
		&i.DistrictID,
		&i.DistrictName,
		&i.Name,
		&i.Role,
		&i.Phone,
		&i.Email,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listContactsByDistrict = `-- name: ListContactsByDistrict :many
SELECT
    c.id, c.district_id, d.name AS district_name, c.name, c.role,
    c.phone, c.email, c.is_active, c.created_at
FROM renjana_contacts c
JOIN renjana_districts d ON d.id = c.district_id
ORDER BY d.name ASC, c.name ASC
`

type ListContactsByDistrictRow struct {
	ID           int64          `json:"id"`
	DistrictID   int64          `json:"district_id"`
	DistrictName string         `json:"district_name"`
	Name         string         `json:"name"`
	Role         string         `json:"role"`
	Phone        sql.NullString `json:"phone"`
	Email        sql.NullString `json:"email"`
	IsActive     bool           `json:"is_active"`
	CreatedAt    time.Time      `json:"created_at"`
}

func (q *Queries) ListContactsByDistrict(ctx context.Context) ([]ListContactsByDistrictRow, error) {
	rows, err := q.db.QueryContext(ctx, listContactsByDistrict)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContactsByDistrictRow
	for rows.Next() {
		var i ListContactsByDistrictRow
		if err := rows.Scan(
			&i.ID,
			&i.DistrictID,
			&i.DistrictName,
			&i.Name,
			&i.Role,
			&i.Phone,
			&i.Email,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactsPaginated = `-- name: ListContactsPaginated :many
SELECT
    c.id, c.district_id, d.name AS district_name, c.name, c.role,
    c.phone, c.email, c.is_active, c.created_at
FROM renjana_contacts c
JOIN renjana_districts d ON d.id = c.district_id
WHERE (?1 IS NULL OR ?1 = ''
       OR c.name LIKE '%' || ?1 || '%'
       OR c.role LIKE '%' || ?1 || '%'
       OR d.name LIKE '%' || ?1 || '%')
  AND (?2 = 0 OR c.district_id = ?2)
ORDER BY d.name ASC, c.name ASC
LIMIT ?3 OFFSET ?4
`

type ListContactsPaginatedParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Limit   int64       `json:"limit"`
	Offset  int64       `json:"offset"`
}

type ListContactsPaginatedRow struct {
	ID           int64          `json:"id"`
	DistrictID   int64          `json:"district_id"`
	DistrictName string         `json:"district_name"`
	Name         string         `json:"name"`
	Role         string         `json:"role"`
	Phone        sql.NullString `json:"phone"`
	Email        sql.NullString `json:"email"`
	IsActive     bool           `json:"is_active"`
	CreatedAt    time.Time      `json:"created_at"`
}

func (q *Queries) ListContactsPaginated(ctx context.Context, arg ListContactsPaginatedParams) ([]ListContactsPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, listContactsPaginated,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContactsPaginatedRow
	for rows.Next() {
		var i ListContactsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.DistrictID,
			&i.DistrictName,
			&i.Name,
			&i.Role,
			&i.Phone,
			&i.Email,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContact = `-- name: UpdateContact :execrows
UPDATE renjana_contacts
SET district_id = ?, name = ?, role = ?, phone = ?, email = ?, is_active = ?
WHERE id = ?
`

type UpdateContactParams struct {
	DistrictID int64          `json:"district_id"`
	Name       string         `json:"name"`
	Role       string         `json:"role"`
	Phone      sql.NullString `json:"phone"`
	Email      sql.NullString `json:"email"`
	IsActive   bool           `json:"is_active"`
	ID         int64          `json:"id"`
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateContact,
		arg.DistrictID,
		arg.Name,
		arg.Role,
		arg.Phone,
		arg.Email,
		arg.IsActive,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
