// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: districts.sql

package queries

import (
	"context"
)

const getActiveDistricts = `-- name: GetActiveDistricts :many
SELECT id, name, is_active, created_at
FROM renjana_districts
WHERE is_active = 1
ORDER BY name
`

func (q *Queries) GetActiveDistricts(ctx context.Context) ([]RenjanaDistrict, error) {
	rows, err := q.db.QueryContext(ctx, getActiveDistricts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenjanaDistrict
	for rows.Next() {
		var i RenjanaDistrict
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllDistricts = `-- name: GetAllDistricts :many
SELECT id, name, is_active, created_at
FROM renjana_districts
ORDER BY name
`

func (q *Queries) GetAllDistricts(ctx context.Context) ([]RenjanaDistrict, error) {
	rows, err := q.db.QueryContext(ctx, getAllDistricts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenjanaDistrict
	for rows.Next() {
		var i RenjanaDistrict
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistrictByID = `-- name: GetDistrictByID :one
SELECT id, name, is_active, created_at
FROM renjana_districts
WHERE id = ?
`

func (q *Queries) GetDistrictByID(ctx context.Context, id int64) (RenjanaDistrict, error) {
	row := q.db.QueryRowContext(ctx, getDistrictByID, id)
	var i RenjanaDistrict
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
