// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package queries

import (
	"context"
)

const countDocumentsFiltered = `-- name: CountDocumentsFiltered :one
SELECT COUNT(*) AS total
FROM renjana_documents
WHERE (?1 IS NULL OR ?1 = '' OR category = ?1)
`

func (q *Queries) CountDocumentsFiltered(ctx context.Context, dollar_1 interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDocumentsFiltered, dollar_1)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const listDocumentsPaginated = `-- name: ListDocumentsPaginated :many
SELECT id, title, file_url, category, version, file_size, description, uploaded_by, uploaded_at
FROM renjana_documents
WHERE (?1 IS NULL OR ?1 = '' OR category = ?1)
ORDER BY uploaded_at DESC
LIMIT ?2 OFFSET ?3
`

type ListDocumentsPaginatedParams struct {
	Column1 interface{} `json:"column_1"`
	Limit   int64       `json:"limit"`
	Offset  int64       `json:"offset"`
}

func (q *Queries) ListDocumentsPaginated(ctx context.Context, arg ListDocumentsPaginatedParams) ([]RenjanaDocument, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsPaginated, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenjanaDocument
	for rows.Next() {
		var i RenjanaDocument
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FileUrl,
			&i.Category,
			&i.Version,
			&i.FileSize,
			&i.Description,
			&i.UploadedBy,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
