// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const countDocumentsFiltered = `-- name: CountDocumentsFiltered :one
SELECT COUNT(*) AS total
FROM renjana_documents
WHERE (?1 IS NULL OR ?1 = '' OR category = ?1)
`

func (q *Queries) CountDocumentsFiltered(ctx context.Context, dollar_1 interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDocumentsFiltered, dollar_1)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO renjana_documents (
    title, file_url, category, version, file_size, description, original_name, uploaded_by
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateDocumentParams struct {
	Title        string         `json:"title"`
	FileUrl      string         `json:"file_url"`
	Category     string         `json:"category"`
	Version      int64          `json:"version"`
	FileSize     sql.NullInt64  `json:"file_size"`
	Description  sql.NullString `json:"description"`
	OriginalName string         `json:"original_name"`
	UploadedBy   sql.NullInt64  `json:"uploaded_by"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.Title,
		arg.FileUrl,
		arg.Category,
		arg.Version,
		arg.FileSize,
		arg.Description,
		arg.OriginalName,
		arg.UploadedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteDocument = `-- name: DeleteDocument :execrows
DELETE FROM renjana_documents WHERE id = ?
`

func (q *Queries) DeleteDocument(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDocument, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDocumentByID = `-- name: GetDocumentByID :one

SELECT id, title, file_url, category, version, file_size, description, original_name, uploaded_by, uploaded_at
FROM renjana_documents
WHERE id = ?
`

type GetDocumentByIDRow struct {
	ID           int64          `json:"id"`
	Title        string         `json:"title"`
	FileUrl      string         `json:"file_url"`
	Category     string         `json:"category"`
	Version      int64          `json:"version"`
	FileSize     sql.NullInt64  `json:"file_size"`
	Description  sql.NullString `json:"description"`
	OriginalName string         `json:"original_name"`
	UploadedBy   sql.NullInt64  `json:"uploaded_by"`
	UploadedAt   time.Time      `json:"uploaded_at"`
}

// ============================================================================
// CRUD for document management (admin only)
// ============================================================================
func (q *Queries) GetDocumentByID(ctx context.Context, id int64) (GetDocumentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getDocumentByID, id)
	var i GetDocumentByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.FileUrl,
		&i.Category,
		&i.Version,
		&i.FileSize,
		&i.Description,
		&i.OriginalName,
		&i.UploadedBy,
		&i.UploadedAt,
	)
	return i, err
}

const listDocumentsPaginated = `-- name: ListDocumentsPaginated :many
SELECT id, title, file_url, category, version, file_size, description, original_name, uploaded_by, uploaded_at
FROM renjana_documents
WHERE (?1 IS NULL OR ?1 = '' OR category = ?1)
ORDER BY uploaded_at DESC
LIMIT ?2 OFFSET ?3
`

type ListDocumentsPaginatedParams struct {
	Column1 interface{} `json:"column_1"`
	Limit   int64       `json:"limit"`
	Offset  int64       `json:"offset"`
}

type ListDocumentsPaginatedRow struct {
	ID           int64          `json:"id"`
	Title        string         `json:"title"`
	FileUrl      string         `json:"file_url"`
	Category     string         `json:"category"`
	Version      int64          `json:"version"`
	FileSize     sql.NullInt64  `json:"file_size"`
	Description  sql.NullString `json:"description"`
	OriginalName string         `json:"original_name"`
	UploadedBy   sql.NullInt64  `json:"uploaded_by"`
	UploadedAt   time.Time      `json:"uploaded_at"`
}

func (q *Queries) ListDocumentsPaginated(ctx context.Context, arg ListDocumentsPaginatedParams) ([]ListDocumentsPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsPaginated, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsPaginatedRow
	for rows.Next() {
		var i ListDocumentsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FileUrl,
			&i.Category,
			&i.Version,
			&i.FileSize,
			&i.Description,
			&i.OriginalName,
			&i.UploadedBy,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocument = `-- name: UpdateDocument :execrows
UPDATE renjana_documents
SET title = ?, file_url = ?, category = ?, version = ?,
    file_size = ?, description = ?, original_name = ?
WHERE id = ?
`

type UpdateDocumentParams struct {
	Title        string         `json:"title"`
	FileUrl      string         `json:"file_url"`
	Category     string         `json:"category"`
	Version      int64          `json:"version"`
	FileSize     sql.NullInt64  `json:"file_size"`
	Description  sql.NullString `json:"description"`
	OriginalName string         `json:"original_name"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDocument,
		arg.Title,
		arg.FileUrl,
		arg.Category,
		arg.Version,
		arg.FileSize,
		arg.Description,
		arg.OriginalName,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
