// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: education.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const countEducationFiltered = `-- name: CountEducationFiltered :one
SELECT COUNT(*) AS total
FROM renjana_education
WHERE (?1 IS NULL OR ?1 = '' OR category = ?1)
  AND (?2 IS NULL OR is_published = ?2)
`

type CountEducationFilteredParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) CountEducationFiltered(ctx context.Context, arg CountEducationFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEducationFiltered, arg.Column1, arg.Column2)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getEducationByID = `-- name: GetEducationByID :one
SELECT id, title, category, body, age_group, duration_minutes, is_published, cover_image, passing_score, total_modules, is_course, created_at, updated_at
FROM renjana_education
WHERE id = ?
`

type GetEducationByIDRow struct {
	ID              int64          `json:"id"`
	Title           string         `json:"title"`
	Category        string         `json:"category"`
	Body            string         `json:"body"`
	AgeGroup        sql.NullString `json:"age_group"`
	DurationMinutes sql.NullInt64  `json:"duration_minutes"`
	IsPublished     bool           `json:"is_published"`
	CoverImage      sql.NullString `json:"cover_image"`
	PassingScore    int64          `json:"passing_score"`
	TotalModules    int64          `json:"total_modules"`
	IsCourse        bool           `json:"is_course"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

func (q *Queries) GetEducationByID(ctx context.Context, id int64) (GetEducationByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getEducationByID, id)
	var i GetEducationByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Body,
		&i.AgeGroup,
		&i.DurationMinutes,
		&i.IsPublished,
		&i.CoverImage,
		&i.PassingScore,
		&i.TotalModules,
		&i.IsCourse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEducationPaginated = `-- name: ListEducationPaginated :many
SELECT id, title, category, body, age_group, duration_minutes, is_published, cover_image, passing_score, total_modules, is_course, created_at, updated_at
FROM renjana_education
WHERE (?1 IS NULL OR ?1 = '' OR category = ?1)
  AND (?2 IS NULL OR is_published = ?2)
ORDER BY created_at DESC
LIMIT ?3 OFFSET ?4
`

type ListEducationPaginatedParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Limit   int64       `json:"limit"`
	Offset  int64       `json:"offset"`
}

type ListEducationPaginatedRow struct {
	ID              int64          `json:"id"`
	Title           string         `json:"title"`
	Category        string         `json:"category"`
	Body            string         `json:"body"`
	AgeGroup        sql.NullString `json:"age_group"`
	DurationMinutes sql.NullInt64  `json:"duration_minutes"`
	IsPublished     bool           `json:"is_published"`
	CoverImage      sql.NullString `json:"cover_image"`
	PassingScore    int64          `json:"passing_score"`
	TotalModules    int64          `json:"total_modules"`
	IsCourse        bool           `json:"is_course"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

func (q *Queries) ListEducationPaginated(ctx context.Context, arg ListEducationPaginatedParams) ([]ListEducationPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, listEducationPaginated,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEducationPaginatedRow
	for rows.Next() {
		var i ListEducationPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Category,
			&i.Body,
			&i.AgeGroup,
			&i.DurationMinutes,
			&i.IsPublished,
			&i.CoverImage,
			&i.PassingScore,
			&i.TotalModules,
			&i.IsCourse,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
