// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: education_lms.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const countPassedAttempts = `-- name: CountPassedAttempts :one
SELECT COUNT(*) AS total
FROM renjana_quiz_attempts
WHERE user_id = ? AND course_id = ? AND passed = 1
`

type CountPassedAttemptsParams struct {
	UserID   int64 `json:"user_id"`
	CourseID int64 `json:"course_id"`
}

func (q *Queries) CountPassedAttempts(ctx context.Context, arg CountPassedAttemptsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPassedAttempts, arg.UserID, arg.CourseID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createCertificate = `-- name: CreateCertificate :exec
INSERT INTO renjana_certificates (user_id, course_id, certificate_code, score, issued_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateCertificateParams struct {
	UserID          int64     `json:"user_id"`
	CourseID        int64     `json:"course_id"`
	CertificateCode string    `json:"certificate_code"`
	Score           int64     `json:"score"`
	IssuedAt        time.Time `json:"issued_at"`
}

func (q *Queries) CreateCertificate(ctx context.Context, arg CreateCertificateParams) error {
	_, err := q.db.ExecContext(ctx, createCertificate,
		arg.UserID,
		arg.CourseID,
		arg.CertificateCode,
		arg.Score,
		arg.IssuedAt,
	)
	return err
}

const createQuizAttempt = `-- name: CreateQuizAttempt :exec
INSERT INTO renjana_quiz_attempts (user_id, course_id, score, total_questions, passed, answers, started_at, completed_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateQuizAttemptParams struct {
	UserID         int64          `json:"user_id"`
	CourseID       int64          `json:"course_id"`
	Score          int64          `json:"score"`
	TotalQuestions int64          `json:"total_questions"`
	Passed         bool           `json:"passed"`
	Answers        sql.NullString `json:"answers"`
	StartedAt      time.Time      `json:"started_at"`
	CompletedAt    sql.NullTime   `json:"completed_at"`
}

func (q *Queries) CreateQuizAttempt(ctx context.Context, arg CreateQuizAttemptParams) error {
	_, err := q.db.ExecContext(ctx, createQuizAttempt,
		arg.UserID,
		arg.CourseID,
		arg.Score,
		arg.TotalQuestions,
		arg.Passed,
		arg.Answers,
		arg.StartedAt,
		arg.CompletedAt,
	)
	return err
}

const getBestQuizAttempt = `-- name: GetBestQuizAttempt :one
SELECT id, user_id, course_id, score, total_questions, passed, answers, started_at, completed_at
FROM renjana_quiz_attempts
WHERE user_id = ? AND course_id = ?
ORDER BY score DESC, completed_at DESC
LIMIT 1
`

type GetBestQuizAttemptParams struct {
	UserID   int64 `json:"user_id"`
	CourseID int64 `json:"course_id"`
}

func (q *Queries) GetBestQuizAttempt(ctx context.Context, arg GetBestQuizAttemptParams) (RenjanaQuizAttempt, error) {
	row := q.db.QueryRowContext(ctx, getBestQuizAttempt, arg.UserID, arg.CourseID)
	var i RenjanaQuizAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.Score,
		&i.TotalQuestions,
		&i.Passed,
		&i.Answers,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getCertificateByCode = `-- name: GetCertificateByCode :one
SELECT c.id, c.user_id, c.course_id, c.certificate_code, c.score, c.issued_at,
       u.name AS user_name, u.email AS user_email,
       e.title AS course_title, e.category AS course_category
FROM renjana_certificates c
JOIN users u ON c.user_id = u.id
JOIN renjana_education e ON c.course_id = e.id
WHERE c.certificate_code = ?
`

type GetCertificateByCodeRow struct {
	ID              int64     `json:"id"`
	UserID          int64     `json:"user_id"`
	CourseID        int64     `json:"course_id"`
	CertificateCode string    `json:"certificate_code"`
	Score           int64     `json:"score"`
	IssuedAt        time.Time `json:"issued_at"`
	UserName        string    `json:"user_name"`
	UserEmail       string    `json:"user_email"`
	CourseTitle     string    `json:"course_title"`
	CourseCategory  string    `json:"course_category"`
}

func (q *Queries) GetCertificateByCode(ctx context.Context, certificateCode string) (GetCertificateByCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getCertificateByCode, certificateCode)
	var i GetCertificateByCodeRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.CertificateCode,
		&i.Score,
		&i.IssuedAt,
		&i.UserName,
		&i.UserEmail,
		&i.CourseTitle,
		&i.CourseCategory,
	)
	return i, err
}

const getCertificateByUserAndCourse = `-- name: GetCertificateByUserAndCourse :one
SELECT id, user_id, course_id, certificate_code, score, issued_at
FROM renjana_certificates
WHERE user_id = ? AND course_id = ?
`

type GetCertificateByUserAndCourseParams struct {
	UserID   int64 `json:"user_id"`
	CourseID int64 `json:"course_id"`
}

func (q *Queries) GetCertificateByUserAndCourse(ctx context.Context, arg GetCertificateByUserAndCourseParams) (RenjanaCertificate, error) {
	row := q.db.QueryRowContext(ctx, getCertificateByUserAndCourse, arg.UserID, arg.CourseID)
	var i RenjanaCertificate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.CertificateCode,
		&i.Score,
		&i.IssuedAt,
	)
	return i, err
}

const getCourseModuleByID = `-- name: GetCourseModuleByID :one
SELECT id, course_id, title, content, video_url, order_index, created_at
FROM renjana_course_modules
WHERE id = ?
`

func (q *Queries) GetCourseModuleByID(ctx context.Context, id int64) (RenjanaCourseModule, error) {
	row := q.db.QueryRowContext(ctx, getCourseModuleByID, id)
	var i RenjanaCourseModule
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Content,
		&i.VideoUrl,
		&i.OrderIndex,
		&i.CreatedAt,
	)
	return i, err
}

const getCourseProgress = `-- name: GetCourseProgress :one
SELECT id, user_id, course_id, completed_modules, total_modules, completed, started_at, completed_at
FROM renjana_course_progress
WHERE user_id = ? AND course_id = ?
`

type GetCourseProgressParams struct {
	UserID   int64 `json:"user_id"`
	CourseID int64 `json:"course_id"`
}

func (q *Queries) GetCourseProgress(ctx context.Context, arg GetCourseProgressParams) (RenjanaCourseProgress, error) {
	row := q.db.QueryRowContext(ctx, getCourseProgress, arg.UserID, arg.CourseID)
	var i RenjanaCourseProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.CompletedModules,
		&i.TotalModules,
		&i.Completed,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getEducationCourseByID = `-- name: GetEducationCourseByID :one
SELECT id, title, category, body, age_group, duration_minutes, is_published, cover_image, passing_score, total_modules, is_course, created_at, updated_at
FROM renjana_education
WHERE id = ? AND is_course = 1
`

type GetEducationCourseByIDRow struct {
	ID              int64          `json:"id"`
	Title           string         `json:"title"`
	Category        string         `json:"category"`
	Body            string         `json:"body"`
	AgeGroup        sql.NullString `json:"age_group"`
	DurationMinutes sql.NullInt64  `json:"duration_minutes"`
	IsPublished     bool           `json:"is_published"`
	CoverImage      sql.NullString `json:"cover_image"`
	PassingScore    int64          `json:"passing_score"`
	TotalModules    int64          `json:"total_modules"`
	IsCourse        bool           `json:"is_course"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

func (q *Queries) GetEducationCourseByID(ctx context.Context, id int64) (GetEducationCourseByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getEducationCourseByID, id)
	var i GetEducationCourseByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Body,
		&i.AgeGroup,
		&i.DurationMinutes,
		&i.IsPublished,
		&i.CoverImage,
		&i.PassingScore,
		&i.TotalModules,
		&i.IsCourse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuizAttemptByID = `-- name: GetQuizAttemptByID :one
SELECT id, user_id, course_id, score, total_questions, passed, answers, started_at, completed_at
FROM renjana_quiz_attempts
WHERE id = ?
`

func (q *Queries) GetQuizAttemptByID(ctx context.Context, id int64) (RenjanaQuizAttempt, error) {
	row := q.db.QueryRowContext(ctx, getQuizAttemptByID, id)
	var i RenjanaQuizAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.Score,
		&i.TotalQuestions,
		&i.Passed,
		&i.Answers,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getQuizQuestionByID = `-- name: GetQuizQuestionByID :one
SELECT id, course_id, question, options, correct_option, order_index, created_at
FROM renjana_quiz_questions
WHERE id = ?
`

func (q *Queries) GetQuizQuestionByID(ctx context.Context, id int64) (RenjanaQuizQuestion, error) {
	row := q.db.QueryRowContext(ctx, getQuizQuestionByID, id)
	var i RenjanaQuizQuestion
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Question,
		&i.Options,
		&i.CorrectOption,
		&i.OrderIndex,
		&i.CreatedAt,
	)
	return i, err
}

const listCourseModules = `-- name: ListCourseModules :many
SELECT id, course_id, title, content, video_url, order_index, created_at
FROM renjana_course_modules
WHERE course_id = ?
ORDER BY order_index ASC
`

func (q *Queries) ListCourseModules(ctx context.Context, courseID int64) ([]RenjanaCourseModule, error) {
	rows, err := q.db.QueryContext(ctx, listCourseModules, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenjanaCourseModule
	for rows.Next() {
		var i RenjanaCourseModule
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.Content,
			&i.VideoUrl,
			&i.OrderIndex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEducationCourses = `-- name: ListEducationCourses :many
SELECT id, title, category, body, age_group, duration_minutes, is_published, cover_image, passing_score, total_modules, is_course, created_at, updated_at
FROM renjana_education
WHERE is_course = 1 AND is_published = 1
ORDER BY created_at DESC
`

type ListEducationCoursesRow struct {
	ID              int64          `json:"id"`
	Title           string         `json:"title"`
	Category        string         `json:"category"`
	Body            string         `json:"body"`
	AgeGroup        sql.NullString `json:"age_group"`
	DurationMinutes sql.NullInt64  `json:"duration_minutes"`
	IsPublished     bool           `json:"is_published"`
	CoverImage      sql.NullString `json:"cover_image"`
	PassingScore    int64          `json:"passing_score"`
	TotalModules    int64          `json:"total_modules"`
	IsCourse        bool           `json:"is_course"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

func (q *Queries) ListEducationCourses(ctx context.Context) ([]ListEducationCoursesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEducationCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEducationCoursesRow
	for rows.Next() {
		var i ListEducationCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Category,
			&i.Body,
			&i.AgeGroup,
			&i.DurationMinutes,
			&i.IsPublished,
			&i.CoverImage,
			&i.PassingScore,
			&i.TotalModules,
			&i.IsCourse,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuizAttemptsByUserAndCourse = `-- name: ListQuizAttemptsByUserAndCourse :many
SELECT id, user_id, course_id, score, total_questions, passed, answers, started_at, completed_at
FROM renjana_quiz_attempts
WHERE user_id = ? AND course_id = ?
ORDER BY completed_at DESC
`

type ListQuizAttemptsByUserAndCourseParams struct {
	UserID   int64 `json:"user_id"`
	CourseID int64 `json:"course_id"`
}

func (q *Queries) ListQuizAttemptsByUserAndCourse(ctx context.Context, arg ListQuizAttemptsByUserAndCourseParams) ([]RenjanaQuizAttempt, error) {
	rows, err := q.db.QueryContext(ctx, listQuizAttemptsByUserAndCourse, arg.UserID, arg.CourseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenjanaQuizAttempt
	for rows.Next() {
		var i RenjanaQuizAttempt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CourseID,
			&i.Score,
			&i.TotalQuestions,
			&i.Passed,
			&i.Answers,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuizQuestions = `-- name: ListQuizQuestions :many
SELECT id, course_id, question, options, correct_option, order_index, created_at
FROM renjana_quiz_questions
WHERE course_id = ?
ORDER BY order_index ASC
`

func (q *Queries) ListQuizQuestions(ctx context.Context, courseID int64) ([]RenjanaQuizQuestion, error) {
	rows, err := q.db.QueryContext(ctx, listQuizQuestions, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenjanaQuizQuestion
	for rows.Next() {
		var i RenjanaQuizQuestion
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Question,
			&i.Options,
			&i.CorrectOption,
			&i.OrderIndex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserCertificates = `-- name: ListUserCertificates :many
SELECT c.id, c.user_id, c.course_id, c.certificate_code, c.score, c.issued_at,
       u.name AS user_name, u.email AS user_email,
       e.title AS course_title, e.category AS course_category
FROM renjana_certificates c
JOIN users u ON c.user_id = u.id
JOIN renjana_education e ON c.course_id = e.id
WHERE c.user_id = ?
ORDER BY c.issued_at DESC
`

type ListUserCertificatesRow struct {
	ID              int64     `json:"id"`
	UserID          int64     `json:"user_id"`
	CourseID        int64     `json:"course_id"`
	CertificateCode string    `json:"certificate_code"`
	Score           int64     `json:"score"`
	IssuedAt        time.Time `json:"issued_at"`
	UserName        string    `json:"user_name"`
	UserEmail       string    `json:"user_email"`
	CourseTitle     string    `json:"course_title"`
	CourseCategory  string    `json:"course_category"`
}

func (q *Queries) ListUserCertificates(ctx context.Context, userID int64) ([]ListUserCertificatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserCertificates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserCertificatesRow
	for rows.Next() {
		var i ListUserCertificatesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CourseID,
			&i.CertificateCode,
			&i.Score,
			&i.IssuedAt,
			&i.UserName,
			&i.UserEmail,
			&i.CourseTitle,
			&i.CourseCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCourseProgress = `-- name: UpsertCourseProgress :exec
INSERT INTO renjana_course_progress (user_id, course_id, completed_modules, total_modules, completed, started_at, completed_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(user_id, course_id) DO UPDATE SET
    completed_modules = excluded.completed_modules,
    total_modules = excluded.total_modules,
    completed = excluded.completed,
    completed_at = COALESCE(excluded.completed_at, completed_at)
`

type UpsertCourseProgressParams struct {
	UserID           int64        `json:"user_id"`
	CourseID         int64        `json:"course_id"`
	CompletedModules int64        `json:"completed_modules"`
	TotalModules     int64        `json:"total_modules"`
	Completed        bool         `json:"completed"`
	StartedAt        time.Time    `json:"started_at"`
	CompletedAt      sql.NullTime `json:"completed_at"`
}

func (q *Queries) UpsertCourseProgress(ctx context.Context, arg UpsertCourseProgressParams) error {
	_, err := q.db.ExecContext(ctx, upsertCourseProgress,
		arg.UserID,
		arg.CourseID,
		arg.CompletedModules,
		arg.TotalModules,
		arg.Completed,
		arg.StartedAt,
		arg.CompletedAt,
	)
	return err
}
