// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: innovations.sql

package queries

import (
	"context"
)

const countInnovationsFiltered = `-- name: CountInnovationsFiltered :one
SELECT COUNT(*) AS total
FROM renjana_innovations
WHERE (?1 IS NULL OR ?1 = '' OR category = ?1)
`

func (q *Queries) CountInnovationsFiltered(ctx context.Context, dollar_1 interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, countInnovationsFiltered, dollar_1)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getInnovationByID = `-- name: GetInnovationByID :one
SELECT id, title, year, category, summary, body, author, created_at
FROM renjana_innovations
WHERE id = ?
`

func (q *Queries) GetInnovationByID(ctx context.Context, id int64) (RenjanaInnovation, error) {
	row := q.db.QueryRowContext(ctx, getInnovationByID, id)
	var i RenjanaInnovation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Year,
		&i.Category,
		&i.Summary,
		&i.Body,
		&i.Author,
		&i.CreatedAt,
	)
	return i, err
}

const listInnovationsPaginated = `-- name: ListInnovationsPaginated :many
SELECT id, title, year, category, summary, body, author, created_at
FROM renjana_innovations
WHERE (?1 IS NULL OR ?1 = '' OR category = ?1)
ORDER BY year DESC, created_at DESC
LIMIT ?2 OFFSET ?3
`

type ListInnovationsPaginatedParams struct {
	Column1 interface{} `json:"column_1"`
	Limit   int64       `json:"limit"`
	Offset  int64       `json:"offset"`
}

func (q *Queries) ListInnovationsPaginated(ctx context.Context, arg ListInnovationsPaginatedParams) ([]RenjanaInnovation, error) {
	rows, err := q.db.QueryContext(ctx, listInnovationsPaginated, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenjanaInnovation
	for rows.Next() {
		var i RenjanaInnovation
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Year,
			&i.Category,
			&i.Summary,
			&i.Body,
			&i.Author,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
