// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql"
	"time"
)

type RenjanaAchievement struct {
	ID           int64           `json:"id"`
	Year         int64           `json:"year"`
	MetricKey    string          `json:"metric_key"`
	MetricName   string          `json:"metric_name"`
	Value        float64         `json:"value"`
	Unit         string          `json:"unit"`
	Target       sql.NullFloat64 `json:"target"`
	DisplayOrder int64           `json:"display_order"`
	Icon         sql.NullString  `json:"icon"`
	IconColor    sql.NullString  `json:"icon_color"`
	CreatedAt    time.Time       `json:"created_at"`
}

type RenjanaActivity struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	TypeID      int64          `json:"type_id"`
	DistrictID  int64          `json:"district_id"`
	Description sql.NullString `json:"description"`
	Location    string         `json:"location"`
	Date        time.Time      `json:"date"`
	Time        string         `json:"time"`
	Status      string         `json:"status"`
	CreatedAt   time.Time      `json:"created_at"`
}

type RenjanaActivityType struct {
	ID           int64     `json:"id"`
	Name         string    `json:"name"`
	Color        string    `json:"color"`
	Icon         string    `json:"icon"`
	DisplayOrder int64     `json:"display_order"`
	IsActive     bool      `json:"is_active"`
	CreatedAt    time.Time `json:"created_at"`
}

type RenjanaAnnouncement struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Excerpt     string         `json:"excerpt"`
	Category    string         `json:"category"`
	Slug        sql.NullString `json:"slug"`
	Body        sql.NullString `json:"body"`
	CoverUrl    sql.NullString `json:"cover_url"`
	AuthorID    sql.NullInt64  `json:"author_id"`
	PublishedAt time.Time      `json:"published_at"`
	IsPublished bool           `json:"is_published"`
	CreatedAt   time.Time      `json:"created_at"`
}

type RenjanaCertificate struct {
	ID              int64     `json:"id"`
	UserID          int64     `json:"user_id"`
	CourseID        int64     `json:"course_id"`
	CertificateCode string    `json:"certificate_code"`
	Score           int64     `json:"score"`
	IssuedAt        time.Time `json:"issued_at"`
}

type RenjanaComplaint struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Email       string         `json:"email"`
	Phone       sql.NullString `json:"phone"`
	Category    string         `json:"category"`
	Message     string         `json:"message"`
	Status      string         `json:"status"`
	Response    sql.NullString `json:"response"`
	RespondedBy sql.NullInt64  `json:"responded_by"`
	RespondedAt sql.NullTime   `json:"responded_at"`
	CreatedAt   time.Time      `json:"created_at"`
}

type RenjanaContact struct {
	ID         int64          `json:"id"`
	DistrictID sql.NullInt64  `json:"district_id"`
	Name       string         `json:"name"`
	Role       string         `json:"role"`
	Phone      sql.NullString `json:"phone"`
	Email      sql.NullString `json:"email"`
	IsActive   bool           `json:"is_active"`
	CreatedAt  time.Time      `json:"created_at"`
}

type RenjanaCourseModule struct {
	ID         int64          `json:"id"`
	CourseID   int64          `json:"course_id"`
	Title      string         `json:"title"`
	Content    string         `json:"content"`
	VideoUrl   sql.NullString `json:"video_url"`
	OrderIndex int64          `json:"order_index"`
	CreatedAt  time.Time      `json:"created_at"`
}

type RenjanaCourseProgress struct {
	ID               int64        `json:"id"`
	UserID           int64        `json:"user_id"`
	CourseID         int64        `json:"course_id"`
	CompletedModules int64        `json:"completed_modules"`
	TotalModules     int64        `json:"total_modules"`
	Completed        bool         `json:"completed"`
	StartedAt        time.Time    `json:"started_at"`
	CompletedAt      sql.NullTime `json:"completed_at"`
}

type RenjanaDistrict struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
}

type RenjanaDocument struct {
	ID           int64          `json:"id"`
	Title        string         `json:"title"`
	FileUrl      string         `json:"file_url"`
	Category     string         `json:"category"`
	Version      int64          `json:"version"`
	FileSize     sql.NullInt64  `json:"file_size"`
	Description  sql.NullString `json:"description"`
	UploadedBy   sql.NullInt64  `json:"uploaded_by"`
	UploadedAt   time.Time      `json:"uploaded_at"`
	OriginalName string         `json:"original_name"`
}

type RenjanaEducation struct {
	ID              int64          `json:"id"`
	Title           string         `json:"title"`
	Category        string         `json:"category"`
	Body            string         `json:"body"`
	AgeGroup        sql.NullString `json:"age_group"`
	DurationMinutes sql.NullInt64  `json:"duration_minutes"`
	IsPublished     bool           `json:"is_published"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	CoverImage      sql.NullString `json:"cover_image"`
	PassingScore    int64          `json:"passing_score"`
	TotalModules    int64          `json:"total_modules"`
	IsCourse        bool           `json:"is_course"`
}

type RenjanaInnovation struct {
	ID        int64          `json:"id"`
	Title     string         `json:"title"`
	Year      int64          `json:"year"`
	Category  string         `json:"category"`
	Summary   sql.NullString `json:"summary"`
	Body      sql.NullString `json:"body"`
	Author    sql.NullString `json:"author"`
	CreatedAt time.Time      `json:"created_at"`
}

type RenjanaMedium struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	FileUrl     string         `json:"file_url"`
	MediaType   string         `json:"media_type"`
	ActivityID  sql.NullInt64  `json:"activity_id"`
	DistrictID  sql.NullInt64  `json:"district_id"`
	Caption     sql.NullString `json:"caption"`
	UploadedBy  sql.NullInt64  `json:"uploaded_by"`
	UploadedAt  time.Time      `json:"uploaded_at"`
	IsPublished bool           `json:"is_published"`
	AlbumID     sql.NullString `json:"album_id"`
}

type RenjanaOrganization struct {
	ID              int64          `json:"id"`
	Vision          sql.NullString `json:"vision"`
	Mission         sql.NullString `json:"mission"`
	History         sql.NullString `json:"history"`
	Structure       sql.NullString `json:"structure"`
	ContactEmail    sql.NullString `json:"contact_email"`
	ContactPhone    sql.NullString `json:"contact_phone"`
	Address         sql.NullString `json:"address"`
	SocialInstagram sql.NullString `json:"social_instagram"`
	SocialTiktok    sql.NullString `json:"social_tiktok"`
	SocialYoutube   sql.NullString `json:"social_youtube"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type RenjanaQuizAttempt struct {
	ID             int64          `json:"id"`
	UserID         int64          `json:"user_id"`
	CourseID       int64          `json:"course_id"`
	Score          int64          `json:"score"`
	TotalQuestions int64          `json:"total_questions"`
	Passed         bool           `json:"passed"`
	Answers        sql.NullString `json:"answers"`
	StartedAt      time.Time      `json:"started_at"`
	CompletedAt    sql.NullTime   `json:"completed_at"`
}

type RenjanaQuizQuestion struct {
	ID            int64     `json:"id"`
	CourseID      int64     `json:"course_id"`
	Question      string    `json:"question"`
	Options       string    `json:"options"`
	CorrectOption int64     `json:"correct_option"`
	OrderIndex    int64     `json:"order_index"`
	CreatedAt     time.Time `json:"created_at"`
}

type RenjanaSurvey struct {
	ID              int64          `json:"id"`
	RespondentName  sql.NullString `json:"respondent_name"`
	RespondentEmail sql.NullString `json:"respondent_email"`
	ServiceType     string         `json:"service_type"`
	Rating          int64          `json:"rating"`
	Feedback        sql.NullString `json:"feedback"`
	CreatedAt       time.Time      `json:"created_at"`
}

type RenjanaVolunteer struct {
	ID                int64          `json:"id"`
	Name              string         `json:"name"`
	School            string         `json:"school"`
	DistrictID        int64          `json:"district_id"`
	Phone             sql.NullString `json:"phone"`
	Status            string         `json:"status"`
	AvatarUrl         sql.NullString `json:"avatar_url"`
	JoinedAt          time.Time      `json:"joined_at"`
	IsActive          bool           `json:"is_active"`
	CreatedAt         time.Time      `json:"created_at"`
	ApplicationStatus string         `json:"application_status"`
	ReviewerID        sql.NullInt64  `json:"reviewer_id"`
	ReviewedAt        sql.NullTime   `json:"reviewed_at"`
	RejectionReason   sql.NullString `json:"rejection_reason"`
}

type Session struct {
	ID        string    `json:"id"`
	UserID    int64     `json:"user_id"`
	Data      string    `json:"data"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID            int64          `json:"id"`
	Email         string         `json:"email"`
	Name          string         `json:"name"`
	Password      sql.NullString `json:"password"`
	Avatar        sql.NullString `json:"avatar"`
	Role          string         `json:"role"`
	GoogleID      sql.NullString `json:"google_id"`
	EmailVerified bool           `json:"email_verified"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	DistrictID    sql.NullInt64  `json:"district_id"`
	VolunteerID   sql.NullInt64  `json:"volunteer_id"`
	IsActive      bool           `json:"is_active"`
}
