// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql"
	"time"
)

type Session struct {
	ID        string
	UserID    int64
	Data      string
	ExpiresAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID            int64
	Email         string
	Name          string
	Password      sql.NullString
	Avatar        sql.NullString
	Role          string
	GoogleID      sql.NullString
	EmailVerified bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
