// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization.sql

package queries

import (
	"context"
	"database/sql"
)

const getOrganization = `-- name: GetOrganization :one
SELECT id, vision, mission, history, structure, contact_email, contact_phone,
       address, social_instagram, social_tiktok, social_youtube, updated_at
FROM renjana_organization
WHERE id = 1
`

func (q *Queries) GetOrganization(ctx context.Context) (RenjanaOrganization, error) {
	row := q.db.QueryRowContext(ctx, getOrganization)
	var i RenjanaOrganization
	err := row.Scan(
		&i.ID,
		&i.Vision,
		&i.Mission,
		&i.History,
		&i.Structure,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Address,
		&i.SocialInstagram,
		&i.SocialTiktok,
		&i.SocialYoutube,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOrganization = `-- name: UpsertOrganization :execrows
INSERT INTO renjana_organization (id, vision, mission, history, structure,
    contact_email, contact_phone, address, social_instagram, social_tiktok, social_youtube, updated_at)
VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE SET
    vision = excluded.vision,
    mission = excluded.mission,
    history = excluded.history,
    structure = excluded.structure,
    contact_email = excluded.contact_email,
    contact_phone = excluded.contact_phone,
    address = excluded.address,
    social_instagram = excluded.social_instagram,
    social_tiktok = excluded.social_tiktok,
    social_youtube = excluded.social_youtube,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertOrganizationParams struct {
	Vision          sql.NullString `json:"vision"`
	Mission         sql.NullString `json:"mission"`
	History         sql.NullString `json:"history"`
	Structure       sql.NullString `json:"structure"`
	ContactEmail    sql.NullString `json:"contact_email"`
	ContactPhone    sql.NullString `json:"contact_phone"`
	Address         sql.NullString `json:"address"`
	SocialInstagram sql.NullString `json:"social_instagram"`
	SocialTiktok    sql.NullString `json:"social_tiktok"`
	SocialYoutube   sql.NullString `json:"social_youtube"`
}

func (q *Queries) UpsertOrganization(ctx context.Context, arg UpsertOrganizationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertOrganization,
		arg.Vision,
		arg.Mission,
		arg.History,
		arg.Structure,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.Address,
		arg.SocialInstagram,
		arg.SocialTiktok,
		arg.SocialYoutube,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
