// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: partners.sql

package queries

import (
	"context"
)

const createPartner = `-- name: CreatePartner :exec
INSERT INTO renjana_partners (name, logo_url, website_url, sort_order)
VALUES (?, ?, ?, ?)
`

type CreatePartnerParams struct {
	Name       string `json:"name"`
	LogoUrl    string `json:"logo_url"`
	WebsiteUrl string `json:"website_url"`
	SortOrder  int64  `json:"sort_order"`
}

func (q *Queries) CreatePartner(ctx context.Context, arg CreatePartnerParams) error {
	_, err := q.db.ExecContext(ctx, createPartner,
		arg.Name,
		arg.LogoUrl,
		arg.WebsiteUrl,
		arg.SortOrder,
	)
	return err
}

const deletePartner = `-- name: DeletePartner :exec
DELETE FROM renjana_partners WHERE id = ?
`

func (q *Queries) DeletePartner(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePartner, id)
	return err
}

const getPartnerByID = `-- name: GetPartnerByID :one
SELECT id, name, logo_url, website_url, sort_order, created_at
FROM renjana_partners
WHERE id = ?
`

func (q *Queries) GetPartnerByID(ctx context.Context, id int64) (RenjanaPartner, error) {
	row := q.db.QueryRowContext(ctx, getPartnerByID, id)
	var i RenjanaPartner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LogoUrl,
		&i.WebsiteUrl,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listPartners = `-- name: ListPartners :many
SELECT id, name, logo_url, website_url, sort_order, created_at
FROM renjana_partners
ORDER BY sort_order ASC, id ASC
`

func (q *Queries) ListPartners(ctx context.Context) ([]RenjanaPartner, error) {
	rows, err := q.db.QueryContext(ctx, listPartners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenjanaPartner
	for rows.Next() {
		var i RenjanaPartner
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LogoUrl,
			&i.WebsiteUrl,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePartner = `-- name: UpdatePartner :exec
UPDATE renjana_partners
SET name = ?,
    logo_url = ?,
    website_url = ?,
    sort_order = ?
WHERE id = ?
`

type UpdatePartnerParams struct {
	Name       string `json:"name"`
	LogoUrl    string `json:"logo_url"`
	WebsiteUrl string `json:"website_url"`
	SortOrder  int64  `json:"sort_order"`
	ID         int64  `json:"id"`
}

func (q *Queries) UpdatePartner(ctx context.Context, arg UpdatePartnerParams) error {
	_, err := q.db.ExecContext(ctx, updatePartner,
		arg.Name,
		arg.LogoUrl,
		arg.WebsiteUrl,
		arg.SortOrder,
		arg.ID,
	)
	return err
}
