// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schools.sql

package queries

import (
	"context"
	"database/sql"
)

const countSchools = `-- name: CountSchools :one
SELECT COUNT(*) FROM renjana_schools
`

func (q *Queries) CountSchools(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSchools)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSchool = `-- name: CreateSchool :one
INSERT INTO renjana_schools (name, level, status, kecamatan)
VALUES (?, ?, ?, ?)
RETURNING id, name, level, status, kecamatan, is_active, created_at, updated_at
`

type CreateSchoolParams struct {
	Name      string `json:"name"`
	Level     string `json:"level"`
	Status    string `json:"status"`
	Kecamatan string `json:"kecamatan"`
}

func (q *Queries) CreateSchool(ctx context.Context, arg CreateSchoolParams) (RenjanaSchool, error) {
	row := q.db.QueryRowContext(ctx, createSchool,
		arg.Name,
		arg.Level,
		arg.Status,
		arg.Kecamatan,
	)
	var i RenjanaSchool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Level,
		&i.Status,
		&i.Kecamatan,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSchool = `-- name: DeleteSchool :exec
DELETE FROM renjana_schools WHERE id = ?
`

func (q *Queries) DeleteSchool(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSchool, id)
	return err
}

const getAllSchoolsByLevel = `-- name: GetAllSchoolsByLevel :many
SELECT id, name, level, status, kecamatan, is_active, created_at, updated_at
FROM renjana_schools
WHERE is_active = 1
  AND (? = '' OR level = ?)
ORDER BY name
`

type GetAllSchoolsByLevelParams struct {
	Column1 interface{} `json:"column_1"`
	Level   string      `json:"level"`
}

func (q *Queries) GetAllSchoolsByLevel(ctx context.Context, arg GetAllSchoolsByLevelParams) ([]RenjanaSchool, error) {
	rows, err := q.db.QueryContext(ctx, getAllSchoolsByLevel, arg.Column1, arg.Level)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenjanaSchool
	for rows.Next() {
		var i RenjanaSchool
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Level,
			&i.Status,
			&i.Kecamatan,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSchoolByID = `-- name: GetSchoolByID :one
SELECT id, name, level, status, kecamatan, is_active, created_at, updated_at
FROM renjana_schools
WHERE id = ?
`

func (q *Queries) GetSchoolByID(ctx context.Context, id int64) (RenjanaSchool, error) {
	row := q.db.QueryRowContext(ctx, getSchoolByID, id)
	var i RenjanaSchool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Level,
		&i.Status,
		&i.Kecamatan,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllSchools = `-- name: ListAllSchools :many
SELECT id, name, level, status, kecamatan, is_active
FROM renjana_schools
WHERE is_active = 1
ORDER BY name
`

type ListAllSchoolsRow struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Level     string `json:"level"`
	Status    string `json:"status"`
	Kecamatan string `json:"kecamatan"`
	IsActive  int64  `json:"is_active"`
}

func (q *Queries) ListAllSchools(ctx context.Context) ([]ListAllSchoolsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllSchools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllSchoolsRow
	for rows.Next() {
		var i ListAllSchoolsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Level,
			&i.Status,
			&i.Kecamatan,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchoolsPaginated = `-- name: ListSchoolsPaginated :many
SELECT id, name, level, status, kecamatan, is_active, created_at, updated_at
FROM renjana_schools
ORDER BY name
LIMIT ? OFFSET ?
`

type ListSchoolsPaginatedParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListSchoolsPaginated(ctx context.Context, arg ListSchoolsPaginatedParams) ([]RenjanaSchool, error) {
	rows, err := q.db.QueryContext(ctx, listSchoolsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenjanaSchool
	for rows.Next() {
		var i RenjanaSchool
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Level,
			&i.Status,
			&i.Kecamatan,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSchools = `-- name: SearchSchools :many
SELECT id, name, level, status, kecamatan, is_active
FROM renjana_schools
WHERE is_active = 1
  AND (
    name LIKE '%' || ?1 || '%'
    OR level LIKE '%' || ?1 || '%'
    OR kecamatan LIKE '%' || ?1 || '%'
    OR status LIKE '%' || ?1 || '%'
  )
ORDER BY
  CASE
    WHEN name LIKE ?1 || '%' THEN 0
    WHEN name LIKE '%' || ?1 || '%' THEN 1
    ELSE 2
  END,
  name
LIMIT 20
`

type SearchSchoolsRow struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Level     string `json:"level"`
	Status    string `json:"status"`
	Kecamatan string `json:"kecamatan"`
	IsActive  int64  `json:"is_active"`
}

func (q *Queries) SearchSchools(ctx context.Context, dollar_1 sql.NullString) ([]SearchSchoolsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchSchools, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchSchoolsRow
	for rows.Next() {
		var i SearchSchoolsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Level,
			&i.Status,
			&i.Kecamatan,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchool = `-- name: UpdateSchool :exec
UPDATE renjana_schools
SET name = ?,
    level = ?,
    status = ?,
    kecamatan = ?,
    updated_at = datetime('now')
WHERE id = ?
`

type UpdateSchoolParams struct {
	Name      string `json:"name"`
	Level     string `json:"level"`
	Status    string `json:"status"`
	Kecamatan string `json:"kecamatan"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateSchool(ctx context.Context, arg UpdateSchoolParams) error {
	_, err := q.db.ExecContext(ctx, updateSchool,
		arg.Name,
		arg.Level,
		arg.Status,
		arg.Kecamatan,
		arg.ID,
	)
	return err
}
