// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: surveys.sql

package queries

import (
	"context"
	"database/sql"
)

const countSurveys = `-- name: CountSurveys :one
SELECT COUNT(*) AS total
FROM renjana_surveys
`

func (q *Queries) CountSurveys(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSurveys)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createSurvey = `-- name: CreateSurvey :one
INSERT INTO renjana_surveys (respondent_name, respondent_email, service_type, rating, feedback)
VALUES (?1, ?2, ?3, ?4, ?5)
RETURNING id, respondent_name, respondent_email, service_type, rating, feedback, created_at
`

type CreateSurveyParams struct {
	RespondentName  sql.NullString `json:"respondent_name"`
	RespondentEmail sql.NullString `json:"respondent_email"`
	ServiceType     string         `json:"service_type"`
	Rating          int64          `json:"rating"`
	Feedback        sql.NullString `json:"feedback"`
}

func (q *Queries) CreateSurvey(ctx context.Context, arg CreateSurveyParams) (RenjanaSurvey, error) {
	row := q.db.QueryRowContext(ctx, createSurvey,
		arg.RespondentName,
		arg.RespondentEmail,
		arg.ServiceType,
		arg.Rating,
		arg.Feedback,
	)
	var i RenjanaSurvey
	err := row.Scan(
		&i.ID,
		&i.RespondentName,
		&i.RespondentEmail,
		&i.ServiceType,
		&i.Rating,
		&i.Feedback,
		&i.CreatedAt,
	)
	return i, err
}

const getSurveyByID = `-- name: GetSurveyByID :one
SELECT id, respondent_name, respondent_email, service_type, rating, feedback, created_at
FROM renjana_surveys
WHERE id = ?
`

func (q *Queries) GetSurveyByID(ctx context.Context, id int64) (RenjanaSurvey, error) {
	row := q.db.QueryRowContext(ctx, getSurveyByID, id)
	var i RenjanaSurvey
	err := row.Scan(
		&i.ID,
		&i.RespondentName,
		&i.RespondentEmail,
		&i.ServiceType,
		&i.Rating,
		&i.Feedback,
		&i.CreatedAt,
	)
	return i, err
}

const getSurveyStats = `-- name: GetSurveyStats :one
SELECT
    COUNT(*) AS total,
    ROUND(AVG(rating), 2) AS average_rating,
    SUM(CASE WHEN rating = 5 THEN 1 ELSE 0 END) AS rating_5,
    SUM(CASE WHEN rating = 4 THEN 1 ELSE 0 END) AS rating_4,
    SUM(CASE WHEN rating = 3 THEN 1 ELSE 0 END) AS rating_3,
    SUM(CASE WHEN rating = 2 THEN 1 ELSE 0 END) AS rating_2,
    SUM(CASE WHEN rating = 1 THEN 1 ELSE 0 END) AS rating_1
FROM renjana_surveys
`

type GetSurveyStatsRow struct {
	Total         int64           `json:"total"`
	AverageRating float64         `json:"average_rating"`
	Rating5       sql.NullFloat64 `json:"rating_5"`
	Rating4       sql.NullFloat64 `json:"rating_4"`
	Rating3       sql.NullFloat64 `json:"rating_3"`
	Rating2       sql.NullFloat64 `json:"rating_2"`
	Rating1       sql.NullFloat64 `json:"rating_1"`
}

func (q *Queries) GetSurveyStats(ctx context.Context) (GetSurveyStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getSurveyStats)
	var i GetSurveyStatsRow
	err := row.Scan(
		&i.Total,
		&i.AverageRating,
		&i.Rating5,
		&i.Rating4,
		&i.Rating3,
		&i.Rating2,
		&i.Rating1,
	)
	return i, err
}

const getSurveyStatsByService = `-- name: GetSurveyStatsByService :many
SELECT service_type, COUNT(*) AS total, ROUND(AVG(rating), 2) AS average_rating
FROM renjana_surveys
GROUP BY service_type
ORDER BY total DESC
`

type GetSurveyStatsByServiceRow struct {
	ServiceType   string  `json:"service_type"`
	Total         int64   `json:"total"`
	AverageRating float64 `json:"average_rating"`
}

func (q *Queries) GetSurveyStatsByService(ctx context.Context) ([]GetSurveyStatsByServiceRow, error) {
	rows, err := q.db.QueryContext(ctx, getSurveyStatsByService)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSurveyStatsByServiceRow
	for rows.Next() {
		var i GetSurveyStatsByServiceRow
		if err := rows.Scan(&i.ServiceType, &i.Total, &i.AverageRating); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSurveysPaginated = `-- name: ListSurveysPaginated :many
SELECT id, respondent_name, respondent_email, service_type, rating, feedback, created_at
FROM renjana_surveys
ORDER BY created_at DESC
LIMIT ?1 OFFSET ?2
`

type ListSurveysPaginatedParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListSurveysPaginated(ctx context.Context, arg ListSurveysPaginatedParams) ([]RenjanaSurvey, error) {
	rows, err := q.db.QueryContext(ctx, listSurveysPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenjanaSurvey
	for rows.Next() {
		var i RenjanaSurvey
		if err := rows.Scan(
			&i.ID,
			&i.RespondentName,
			&i.RespondentEmail,
			&i.ServiceType,
			&i.Rating,
			&i.Feedback,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
