// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: surveys.sql

package queries

import (
	"context"
	"database/sql"
)

const countSurveySKM = `-- name: CountSurveySKM :one
SELECT COUNT(*) AS total
FROM renjana_survey_skm
`

func (q *Queries) CountSurveySKM(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSurveySKM)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createSurveySKM = `-- name: CreateSurveySKM :one
INSERT INTO renjana_survey_skm (age, gender, education, occupation, year, q1, q2, q3, q4, q5, q6, q7, q8, q9, feedback)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15)
RETURNING id, age, gender, education, occupation, year, q1, q2, q3, q4, q5, q6, q7, q8, q9, feedback, created_at
`

type CreateSurveySKMParams struct {
	Age        int64          `json:"age"`
	Gender     string         `json:"gender"`
	Education  string         `json:"education"`
	Occupation string         `json:"occupation"`
	Year       int64          `json:"year"`
	Q1         int64          `json:"q1"`
	Q2         int64          `json:"q2"`
	Q3         int64          `json:"q3"`
	Q4         int64          `json:"q4"`
	Q5         int64          `json:"q5"`
	Q6         int64          `json:"q6"`
	Q7         int64          `json:"q7"`
	Q8         int64          `json:"q8"`
	Q9         int64          `json:"q9"`
	Feedback   sql.NullString `json:"feedback"`
}

func (q *Queries) CreateSurveySKM(ctx context.Context, arg CreateSurveySKMParams) (RenjanaSurveySkm, error) {
	row := q.db.QueryRowContext(ctx, createSurveySKM,
		arg.Age,
		arg.Gender,
		arg.Education,
		arg.Occupation,
		arg.Year,
		arg.Q1,
		arg.Q2,
		arg.Q3,
		arg.Q4,
		arg.Q5,
		arg.Q6,
		arg.Q7,
		arg.Q8,
		arg.Q9,
		arg.Feedback,
	)
	var i RenjanaSurveySkm
	err := row.Scan(
		&i.ID,
		&i.Age,
		&i.Gender,
		&i.Education,
		&i.Occupation,
		&i.Year,
		&i.Q1,
		&i.Q2,
		&i.Q3,
		&i.Q4,
		&i.Q5,
		&i.Q6,
		&i.Q7,
		&i.Q8,
		&i.Q9,
		&i.Feedback,
		&i.CreatedAt,
	)
	return i, err
}

const getSurveySKMByEducation = `-- name: GetSurveySKMByEducation :many
SELECT education, COUNT(*) AS count, ROUND(AVG(q1 + q2 + q3 + q4 + q5 + q6 + q7 + q8 + q9) * 100.0 / 36.0, 1) AS avg_score
FROM renjana_survey_skm
GROUP BY education
ORDER BY count DESC
`

type GetSurveySKMByEducationRow struct {
	Education string  `json:"education"`
	Count     int64   `json:"count"`
	AvgScore  float64 `json:"avg_score"`
}

func (q *Queries) GetSurveySKMByEducation(ctx context.Context) ([]GetSurveySKMByEducationRow, error) {
	rows, err := q.db.QueryContext(ctx, getSurveySKMByEducation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSurveySKMByEducationRow
	for rows.Next() {
		var i GetSurveySKMByEducationRow
		if err := rows.Scan(&i.Education, &i.Count, &i.AvgScore); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSurveySKMByGender = `-- name: GetSurveySKMByGender :many
SELECT gender, COUNT(*) AS count, ROUND(AVG(q1 + q2 + q3 + q4 + q5 + q6 + q7 + q8 + q9) * 100.0 / 36.0, 1) AS avg_score
FROM renjana_survey_skm
GROUP BY gender
ORDER BY count DESC
`

type GetSurveySKMByGenderRow struct {
	Gender   string  `json:"gender"`
	Count    int64   `json:"count"`
	AvgScore float64 `json:"avg_score"`
}

func (q *Queries) GetSurveySKMByGender(ctx context.Context) ([]GetSurveySKMByGenderRow, error) {
	rows, err := q.db.QueryContext(ctx, getSurveySKMByGender)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSurveySKMByGenderRow
	for rows.Next() {
		var i GetSurveySKMByGenderRow
		if err := rows.Scan(&i.Gender, &i.Count, &i.AvgScore); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSurveySKMByOccupation = `-- name: GetSurveySKMByOccupation :many
SELECT occupation, COUNT(*) AS count, ROUND(AVG(q1 + q2 + q3 + q4 + q5 + q6 + q7 + q8 + q9) * 100.0 / 36.0, 1) AS avg_score
FROM renjana_survey_skm
GROUP BY occupation
ORDER BY count DESC
`

type GetSurveySKMByOccupationRow struct {
	Occupation string  `json:"occupation"`
	Count      int64   `json:"count"`
	AvgScore   float64 `json:"avg_score"`
}

func (q *Queries) GetSurveySKMByOccupation(ctx context.Context) ([]GetSurveySKMByOccupationRow, error) {
	rows, err := q.db.QueryContext(ctx, getSurveySKMByOccupation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSurveySKMByOccupationRow
	for rows.Next() {
		var i GetSurveySKMByOccupationRow
		if err := rows.Scan(&i.Occupation, &i.Count, &i.AvgScore); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSurveySKMStats = `-- name: GetSurveySKMStats :one
SELECT
    COUNT(*) AS total,
    ROUND(CAST(SUM(q1 + q2 + q3 + q4 + q5 + q6 + q7 + q8 + q9) AS REAL) / (COUNT(*) * 9 * 4) * 100, 1) AS skm_score,
    ROUND(AVG(q1), 2) AS avg_q1,
    ROUND(AVG(q2), 2) AS avg_q2,
    ROUND(AVG(q3), 2) AS avg_q3,
    ROUND(AVG(q4), 2) AS avg_q4,
    ROUND(AVG(q5), 2) AS avg_q5,
    ROUND(AVG(q6), 2) AS avg_q6,
    ROUND(AVG(q7), 2) AS avg_q7,
    ROUND(AVG(q8), 2) AS avg_q8,
    ROUND(AVG(q9), 2) AS avg_q9
FROM renjana_survey_skm
`

type GetSurveySKMStatsRow struct {
	Total    int64   `json:"total"`
	SkmScore float64 `json:"skm_score"`
	AvgQ1    float64 `json:"avg_q1"`
	AvgQ2    float64 `json:"avg_q2"`
	AvgQ3    float64 `json:"avg_q3"`
	AvgQ4    float64 `json:"avg_q4"`
	AvgQ5    float64 `json:"avg_q5"`
	AvgQ6    float64 `json:"avg_q6"`
	AvgQ7    float64 `json:"avg_q7"`
	AvgQ8    float64 `json:"avg_q8"`
	AvgQ9    float64 `json:"avg_q9"`
}

func (q *Queries) GetSurveySKMStats(ctx context.Context) (GetSurveySKMStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getSurveySKMStats)
	var i GetSurveySKMStatsRow
	err := row.Scan(
		&i.Total,
		&i.SkmScore,
		&i.AvgQ1,
		&i.AvgQ2,
		&i.AvgQ3,
		&i.AvgQ4,
		&i.AvgQ5,
		&i.AvgQ6,
		&i.AvgQ7,
		&i.AvgQ8,
		&i.AvgQ9,
	)
	return i, err
}

const listSurveySKMPaginated = `-- name: ListSurveySKMPaginated :many
SELECT id, age, gender, education, occupation, year, q1, q2, q3, q4, q5, q6, q7, q8, q9, feedback, created_at
FROM renjana_survey_skm
ORDER BY created_at DESC
LIMIT ?1 OFFSET ?2
`

type ListSurveySKMPaginatedParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListSurveySKMPaginated(ctx context.Context, arg ListSurveySKMPaginatedParams) ([]RenjanaSurveySkm, error) {
	rows, err := q.db.QueryContext(ctx, listSurveySKMPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenjanaSurveySkm
	for rows.Next() {
		var i RenjanaSurveySkm
		if err := rows.Scan(
			&i.ID,
			&i.Age,
			&i.Gender,
			&i.Education,
			&i.Occupation,
			&i.Year,
			&i.Q1,
			&i.Q2,
			&i.Q3,
			&i.Q4,
			&i.Q5,
			&i.Q6,
			&i.Q7,
			&i.Q8,
			&i.Q9,
			&i.Feedback,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
