// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: volunteers.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const countActiveDistricts = `-- name: CountActiveDistricts :one
SELECT COUNT(DISTINCT district_id) AS total
FROM renjana_volunteers
WHERE is_active = 1
`

// Count distinct districts that have at least one active volunteer
func (q *Queries) CountActiveDistricts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveDistricts)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countActiveVolunteers = `-- name: CountActiveVolunteers :one
SELECT COUNT(*) AS total
FROM renjana_volunteers
WHERE is_active = 1
`

func (q *Queries) CountActiveVolunteers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveVolunteers)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countActiveVolunteersPreviousMonth = `-- name: CountActiveVolunteersPreviousMonth :one
SELECT COUNT(*) AS total
FROM renjana_volunteers
WHERE is_active = 1
  AND joined_at < datetime('now', '-30 days')
`

// Approximation: count all volunteers where is_active = 1, joined_at < 30 days ago
func (q *Queries) CountActiveVolunteersPreviousMonth(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveVolunteersPreviousMonth)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countAllVolunteers = `-- name: CountAllVolunteers :one
SELECT COUNT(*) AS total
FROM renjana_volunteers
`

func (q *Queries) CountAllVolunteers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllVolunteers)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countDistinctSchools = `-- name: CountDistinctSchools :one
SELECT COUNT(DISTINCT school) AS total
FROM renjana_volunteers
WHERE is_active = 1
`

func (q *Queries) CountDistinctSchools(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDistinctSchools)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countVolunteersByDistrict = `-- name: CountVolunteersByDistrict :many
SELECT
    d.id AS district_id,
    d.name AS district_name,
    COUNT(v.id) AS volunteer_count
FROM renjana_districts d
LEFT JOIN renjana_volunteers v ON v.district_id = d.id AND v.is_active = 1
GROUP BY d.id, d.name
ORDER BY volunteer_count DESC, d.name
`

type CountVolunteersByDistrictRow struct {
	DistrictID     int64
	DistrictName   string
	VolunteerCount int64
}

func (q *Queries) CountVolunteersByDistrict(ctx context.Context) ([]CountVolunteersByDistrictRow, error) {
	rows, err := q.db.QueryContext(ctx, countVolunteersByDistrict)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountVolunteersByDistrictRow
	for rows.Next() {
		var i CountVolunteersByDistrictRow
		if err := rows.Scan(&i.DistrictID, &i.DistrictName, &i.VolunteerCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveVolunteersWithLimit = `-- name: GetActiveVolunteersWithLimit :many
SELECT
    v.id,
    v.name,
    v.school,
    v.district_id,
    d.name AS district_name,
    v.status,
    v.avatar_url,
    v.joined_at
FROM renjana_volunteers v
JOIN renjana_districts d ON d.id = v.district_id
WHERE v.is_active = 1
  AND v.status = 'aktif'
ORDER BY v.joined_at DESC
LIMIT ?
`

type GetActiveVolunteersWithLimitRow struct {
	ID           int64
	Name         string
	School       string
	DistrictID   int64
	DistrictName string
	Status       string
	AvatarUrl    sql.NullString
	JoinedAt     time.Time
}

func (q *Queries) GetActiveVolunteersWithLimit(ctx context.Context, limit int64) ([]GetActiveVolunteersWithLimitRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveVolunteersWithLimit, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveVolunteersWithLimitRow
	for rows.Next() {
		var i GetActiveVolunteersWithLimitRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.School,
			&i.DistrictID,
			&i.DistrictName,
			&i.Status,
			&i.AvatarUrl,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
